Knuckles OS: modules/command_handler.c File Reference
command_handler.c File Reference
#include "command_handler.h"
Macros
#define COM1 0x3f8
Functions
char * lexer (char *cmdBuffer)
void com_handler ()
void splashScreen ()
void version ()
void shutdown ()
void loadR3 ()
void loadToPCB (char *name, int classID, int priority, void func())
void setAlarm ()
Variables
int quit = 0
char * history
char alarmTime1 [10]
char alarmMsg1 [30]
char alarmTime2 [10]
char alarmMsg2 [30]
char alarmTime3 [10]
char alarmMsg3 [30]
char alarmTime4 [10]
char alarmMsg4 [30]
int alarmFlag1 = 0
int alarmFlag2 = 0
int alarmFlag3 = 0
int alarmFlag4 = 0
int dontCall1 = 0
int dontCall2 = 0
int dontCall3 = 0
int dontCall4 = 0
Macro Definition Documentation
#define COM1 0x3f8
Definition at line 6 of file command_handler.c.
Function Documentation
void com_handler ()
Procedure: com_handler
Description: Main function of the operating system, in which user input is parsed and executed.
Parameters: None
Returns: Void
Definition at line 39 of file command_handler.c.
References alarmFlag1, alarmFlag2, alarmFlag3, alarmFlag4, alarmMsg1, alarmMsg2, alarmMsg3, alarmTime1, alarmTime2, alarmTime3, application_process, atoi(), block(), count, create(), DEFAULT_DEVICE, E_CMD, E_DAY, E_FORMAT, E_HELP, E_HOUR, E_MIN, E_MONTH, E_PARAMS, E_SEC, E_YEAR, emptyBuffer(), errorHandler(), EXIT, generalHelp(), getDate(), getTime(), helpBlock(), helpBuffer, helpCreate(), helpGetDate(), helpGetTime(), helpLoadr3(), helpPriority(), helpQuit(), helpRemove(), helpResume(), helpSetAlarm(), helpSetDate(), helpSetTime(), helpShow(), helpShowAll(), helpShowBlocked(), helpShowReady(), helpSuspend(), helpUnblock(), helpVersion(), helpYield(), IDLE, loadR3(), loadToPCB(), memset(), NULL, printCount(), printIndex(), quit, READ, resume(), setAlarm(), setDate(), setPriority(), setTime(), setupHistory(), show(), showAll(), showBlocked(), showFirst(), showHistory(), showReady(), shutdown(), splashScreen(), strcat(), strcmp(), strcpy(), strlen(), strtok(), suspend(), sys_req(), unblock(), version(), and WRITE.
                    {
     splashScreen();
     setupHistory();
   char cmdBuffer[65];
     char helpBuffer[100];
   char timeBuffer[12];
   char timeStr[12];
   char dateBuffer[12];
   char dateStr[12];
   char alarmBuffer[100];
   // char alarmStr[100];
     error_t error;
   int bufferSize;
   int count;
     while(!quit){
     bufferSize = 65;
     count = 0;
     memset(helpBuffer, '\0', sizeof(helpBuffer));
     /* For read */
         sys_req(IDLE, DEFAULT_DEVICE, NULL, NULL);
         strcpy(cmdBuffer, "\033[31mknuckles > \033[0m");
     count = strlen(cmdBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
         count = 0;
         emptyBuffer(helpBuffer, &count);
         memset(cmdBuffer, '\0', sizeof(cmdBuffer));
         sys_req(READ, DEFAULT_DEVICE, cmdBuffer, &bufferSize);
         char* commands = strtok(cmdBuffer, " ");
         if(commands == NULL) {
             continue;
         }
         else if(!strcmp(commands, "quit")) {
             memset( helpBuffer, '\0', sizeof(helpBuffer));
         strcpy(helpBuffer, "Confirm shutdown? [Y/N]:\n");
         count = strlen(helpBuffer);
         sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
             memset(cmdBuffer, '\0', sizeof(cmdBuffer));
             sys_req(READ, DEFAULT_DEVICE, cmdBuffer, &bufferSize);
             char* ans = strtok(cmdBuffer, " ");
             if(!strcmp(ans,"Y") || !strcmp(ans,"y")){
             shutdown();
             }
       else{
         memset( helpBuffer, '\0', sizeof(helpBuffer));
         strcpy(helpBuffer, "Returning to terminal...\n");
         count = strlen(helpBuffer);
         sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
         }
         }
         else if(!strcmp(commands, "version")) {
             version();
         }
         // Version R2
         else if(!strcmp(commands, "suspend")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
         continue;
       }
             char *name = commands;
             error = suspend(name);
             errorHandler(error);
         }
         else if(!strcmp(commands, "resume")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
             char *name = commands;
             error = resume(name);
             errorHandler(error);
         }
         else if(!strcmp(commands, "priority")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
             char *name = commands;
             commands = strtok(NULL, " ");
             int priority = atoi(commands);
             if(priority < 0 || priority > 9){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
             error = setPriority(name, priority);
             errorHandler(error);
         }
         else if(!strcmp(commands, "show")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
         error = E_PARAMS;
                 errorHandler(error);
         continue;
       }
             char *name = commands;
             show(name);
         }
         else if(!strcmp(commands, "showall")) {
             showAll();
         }
         else if(!strcmp(commands, "showready")) {
             showReady();
         }
         else if(!strcmp(commands, "showblocked")) {
             showBlocked();
         }
     // ---- temporary ----
         else if(!strcmp(commands, "create")) {
             commands = strtok(NULL, " ");
             if(commands == NULL || strlen(commands) < 8 || strlen(commands) > 30){
         error = E_PARAMS;
                 errorHandler(error);
                 continue;
       }
             char *name = commands;
             commands = strtok(NULL, " ");
             int pClass;
             if(strcmp(commands, "application") && strcmp(commands, "system")){
         error = E_PARAMS;
                 errorHandler(error);
                 continue;
       }
             if(!strcmp(commands, "application")) {
                 pClass = 1;
             }
             else if(!strcmp(commands, "system")) {
                 pClass = 0;
             }
             commands = strtok(NULL, " ");
             int priority = atoi(commands);
             if(priority < 0 || priority > 9){
         error = E_PARAMS;
                 errorHandler(error);
         continue;
       }
             error = create(name, pClass, priority);
             errorHandler(error);
         }
         else if(!strcmp(commands, "remove")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
         error = E_PARAMS;
                 errorHandler(error);
                 continue;
       }
             char *name = commands;
             error = remove(name);
             errorHandler(error);
         }
         else if(!strcmp(commands, "block")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
         error = E_PARAMS;
                 errorHandler(error);
                 continue;
       }
             char *name = commands;
             error = block(name);
             errorHandler(error);
         }
         else if(!strcmp(commands, "unblock")) {
             commands = strtok(NULL, " ");
             if(commands == NULL){
         error = E_PARAMS;
                 errorHandler(error);
                 continue;
       }
             char *name = commands;
             error = unblock(name);
             errorHandler(error);
         }
         // R3
         else if(!strcmp(commands, "loadr3")) {
             loadR3();
         }
         // R4
         else if(!strcmp(commands, "setalarm")){ //placed in real clock header
         //--------Time Parameter---------
             commands = strtok(NULL, " ");
             strcpy(timeBuffer, commands);
                 if(timeBuffer == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
                 int check_hour, check_min, check_sec;
                 check_hour = atoi(timeBuffer);
                 if((strlen(timeBuffer) != 2) || !(0 <= check_hour && check_hour < 24)){
                     error = E_HOUR;
                 errorHandler(error);
                     continue;
                 }
                 strcpy(timeStr, timeBuffer);
       //Minutes-------------------------------------------------------
             commands = strtok(NULL, " ");
                 memset( timeBuffer, '\0', sizeof(timeBuffer));
             strcpy(timeBuffer, commands);
                 if(timeBuffer == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
                 check_min = atoi(timeBuffer);
                 if((strlen(timeBuffer) != 2) || !(0 <= check_min && check_min < 60)){
                     error = E_MIN;
                 errorHandler(error);
                     continue;
                 }
                 strcat(timeStr, timeBuffer);
       //Seconds--------------------------------------------------------
             commands = strtok(NULL, " ");
                 memset(timeBuffer, '\0', sizeof(timeBuffer));
             strcpy(timeBuffer, commands);
                 if(timeBuffer == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
                 check_sec = atoi(timeBuffer);
                 if((strlen(timeBuffer) != 2) || !(0 <= check_sec && check_sec < 60)){
                     error = E_SEC;
                 errorHandler(error);
                     continue;
                 }
                 strcat(timeStr, timeBuffer);
             commands = strtok(NULL, "");
             if(commands == NULL){
         error = E_PARAMS;
                 errorHandler(error);
         continue;
       }
             memset( alarmBuffer, '\0', sizeof(alarmBuffer));
             strcpy(alarmBuffer, commands);
                 if(alarmBuffer == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
             }
             if(strlen(alarmBuffer) <= 0){
                     error = E_FORMAT;
                 errorHandler(error);
                     continue;
                 }
             // strcat(alarmStr, alarmBuffer);
             if(alarmFlag1 == 1){
                 if(alarmFlag2 == 1){
                     if(alarmFlag3 == 1){
                         if(alarmFlag4 == 1){
                         } else{
                             // tell user they must wait for an alarm to be available
                             memset( helpBuffer, '\0', sizeof(helpBuffer));
                         strcpy(helpBuffer, "Out of alarms! (3 maximum for now...):\n");
                         count = strlen(helpBuffer);
                         sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
                             // strcpy(alarmTime4, timeStr);
                             // strcat(alarmMsg4, "Alarm 4: ");
                             // strcat(alarmMsg4, alarmBuffer);
                             // strcat(alarmMsg4, "\n");
                             // alarmFlag4 = 1;
                             // void (*alarmptr)() = &setAlarm;
                             // loadToPCB("Alarm", application_process, 3, alarmptr);
                         }
                     } else{
                         strcpy(alarmTime3, timeStr);
                         strcat(alarmMsg3, "Alarm 3: ");
                         strcat(alarmMsg3, alarmBuffer);
                         strcat(alarmMsg3, "\n");
                         alarmFlag3 = 1;
                         void (*alarmptr)() = &setAlarm;
                         loadToPCB("Alarm", application_process, 3, alarmptr);
                     }
                 } else{
                     strcpy(alarmTime2, timeStr);
                     strcat(alarmMsg2, "Alarm 2: ");
                     strcat(alarmMsg2, alarmBuffer);
                     strcat(alarmMsg2, "\n");
                     alarmFlag2 = 1;
                     void (*alarmptr)() = &setAlarm;
                     loadToPCB("Alarm", application_process, 3, alarmptr);
                 }
             } else{
                 strcpy(alarmTime1, timeStr);
                 strcat(alarmMsg1, "Alarm 1: ");
                 strcat(alarmMsg1, alarmBuffer);
                 strcat(alarmMsg1, "\n");
                 alarmFlag1 = 1;
                 void (*alarmptr)() = &setAlarm;
                 loadToPCB("Alarm", application_process, 3, alarmptr);
             }
             // strcpy(alarmTime, timeStr);
             // strcpy(alarmMsg, alarmBuffer);
             // strcat(alarmMsg, "\n");
             // void (*alarmptr)() = &setAlarm;
             // loadToPCB("Alarm", application_process, 3, alarmptr);
         }
         else if(!strcmp(commands, "help")) {
             commands = strtok(NULL, " ");
             if(!strcmp(commands, "gettime")) {
                 helpGetTime();
             }
             else if(!strcmp(commands, "settime")) {
                 helpSetTime();
             }
             else if(!strcmp(commands, "getdate")) {
                 helpGetDate();
             }
             else if(!strcmp(commands, "setdate")) {
                 helpSetDate();
             }
             else if(!strcmp(commands, "version")) {
                 helpVersion();
             }
             else if(!strcmp(commands, "quit")) {
                 helpQuit();
             }
             else if(!strcmp(commands, "suspend")) {
                 helpSuspend();
             }
             else if(!strcmp(commands, "resume")) {
                 helpResume();
             }
             else if(!strcmp(commands, "priority")) {
                 helpPriority();
             }
             else if(!strcmp(commands, "show")) {
                 helpShow();
             }
             else if(!strcmp(commands, "showall")) {
                 helpShowAll();
             }
             else if(!strcmp(commands, "showready")) {
                 helpShowReady();
             }
             else if(!strcmp(commands, "showblocked")) {
                 helpShowBlocked();
             }
             else if(!strcmp(commands, "create")) {
                 helpCreate();
             }
             else if(!strcmp(commands, "remove")) {
                 helpRemove();
             }
             else if(!strcmp(commands, "block")) {
                 helpBlock();
             }
             else if(!strcmp(commands, "unblock")) {
                 helpUnblock();
             }
             else if(!strcmp(commands, "yield")) {
                 helpYield();
             }
             else if(!strcmp(commands, "loadr3")) {
                 helpLoadr3();
             }
             else if(!strcmp(commands, "setalarm")) {
                 helpSetAlarm();
             }
             else if(!strcmp(commands, NULL)) {
                 generalHelp();
             }
             else {
                 error = E_HELP;
                 errorHandler(error);
             }
         }
         else if(!strcmp(commands, "settime")){
             commands = strtok(NULL, " ");
             strcpy(timeBuffer, commands);
                 if(timeBuffer == NULL){
                     error = E_PARAMS;
                 errorHandler(error);
                     continue;
                 }
                 int check_hour, check_min, check_sec;
       check_hour = atoi(timeBuffer);
       if((strlen(timeBuffer) != 2) || !(0 <= check_hour && check_hour < 24)){
             error = E_HOUR;
                     errorHandler(error);
             continue;
       }
       strcpy(timeStr, timeBuffer);
       strcat(timeStr, ":");
       //Minutes-------------------------------------------------------
             commands = strtok(NULL, " ");
       memset( timeBuffer, '\0', sizeof(timeBuffer));
             strcpy(timeBuffer, commands);
       if(timeBuffer == NULL){
             error = E_PARAMS;
                     errorHandler(error);
             continue;
       }
       check_min = atoi(timeBuffer);
       if((strlen(timeBuffer) != 2) || !(0 <= check_min && check_min < 60)){
             error = E_MIN;
                     errorHandler(error);
             continue;
       }
       strcat(timeStr, timeBuffer);
       strcat(timeStr, ":");
       //Seconds--------------------------------------------------------
             commands = strtok(NULL, " ");
       memset( timeBuffer, '\0', sizeof(timeBuffer));
             strcpy(timeBuffer, commands);
       if(timeBuffer == NULL){
             error = E_PARAMS;
                     errorHandler(error);
             continue;
         }
       check_sec = atoi(timeBuffer);
       if((strlen(timeBuffer) != 2) || !(0 <= check_sec && check_sec < 60)){
                 error = E_SEC;
                         errorHandler(error);
                 continue;
       }
       strcat(timeStr, timeBuffer);
             setTime(timeStr);
     }
     else if(!strcmp(commands, "gettime")){
         getTime();
     }
     else if(!strcmp(commands, "setdate")){
         //Month-------------------------------------
             commands = strtok(NULL, " ");
             strcpy(dateBuffer, commands);
       if(dateBuffer == NULL){
             error = E_PARAMS;
                     errorHandler(error);
             continue;
       }
       int check_month, check_day, check_year;
       check_month = atoi(dateBuffer);
       if((strlen(dateBuffer) != 2) || !(1 <= check_month && check_month <= 12)){
             error = E_MONTH;
                     errorHandler(error);
             continue;
         }
       strcpy(dateStr, dateBuffer);
       strcat(dateStr, "/");
       //Day-------------------------------------------------------
             commands = strtok(NULL, " ");
       memset(dateBuffer, '\0', sizeof(dateBuffer));
             strcpy(dateBuffer, commands);
       if(dateBuffer == NULL){
             error = E_PARAMS;
                     errorHandler(error);
             continue;
       }
       check_day = atoi(dateBuffer);
       if((strlen(dateBuffer) != 2) || !(1 <= check_day && check_day <= 31)){
             error = E_DAY;
                     errorHandler(error);
             continue;
       }
       strcat(dateStr, dateBuffer);
       strcat(dateStr, "/");
       //Year--------------------------------------------------------
             commands = strtok(NULL, " ");
       memset(dateBuffer, '\0', sizeof(dateBuffer));
             strcpy(dateBuffer, commands);
       if(dateBuffer == NULL){
         error = E_PARAMS;
                 errorHandler(error);
         continue;
         }
       check_year = atoi(dateBuffer);
       if((strlen(dateBuffer) != 2) || !(0 <= check_year && check_year <= 99)){
             error = E_YEAR;
                     errorHandler(error);
             continue;
       }
       strcat(dateStr, dateBuffer);
       setDate(dateStr);
     }
         else if(!strcmp(commands, "getdate")){
             getDate();
     }
         else if(!strcmp(commands, "commandindex")){
             printIndex();
     }
         else if(!strcmp(commands, "historycount")){
             printCount();
     }
         else if(!strcmp(commands, "showhistory")){
             showHistory();
     }
         else if(!strcmp(commands, "showfirst")){
             showFirst();
     }
     else{
         memset( helpBuffer, '\0', sizeof(helpBuffer));
             error = E_CMD;
                 errorHandler(error);
         continue;
     }
     }
     sys_req(EXIT, DEFAULT_DEVICE, NULL, NULL);
     return;
 }
char* lexer (char * cmdBuffer)
Definition at line 29 of file command_handler.c.
References NULL, serial_println(), and strtok().
{
     const char *deliminator = " ";
     char *commands = strtok(cmdBuffer, deliminator);
     while(commands != NULL) {
         serial_println(commands);
         commands = strtok(NULL, " ");
     }
     return commands;
 }
void loadR3 ()
Procedure: loadR3
Description: Inputs the required R3 function pointer to the loadToPCB function.
Parameters: None
Returns: Void
Definition at line 601 of file command_handler.c.
References application_process, loadToPCB(), proc1(), proc2(), proc3(), proc4(), and proc5().
              {
     //void (*func1)() = &proc1;
     loadToPCB("proc1", application_process, 3, proc1);
     //void (*func2)() = &proc2;
     loadToPCB("proc2", application_process, 3, proc2);
     //void (*func3)() = &proc3;
     loadToPCB("proc3", application_process, 3, proc3);
     //void (*func4)() = &proc4;
     loadToPCB("proc4", application_process, 3, proc4);
     //void (*func5)() = &proc5;
     loadToPCB("proc5", application_process, 3, proc5);
 }
void loadToPCB (char * name, int classID, int priority, void func())
Definition at line 634 of file command_handler.c.
References addReadyAtEnd(), context::cs, context::ds, context::ebp, context::eflags, context::eip, context::es, context::esp, context::fs, context::gs, memset(), NULL, SetupPCB(), pcb::stackBase, and pcb::stackTop.
{
     PCB* proc = SetupPCB(name, classID, priority);
     if (proc != NULL) {
         Context* newContext = (Context*)(proc->stackTop);
         memset(newContext, 0, sizeof(Context));
         newContext->fs = 0x10;
         newContext->gs = 0x10;
         newContext->ds = 0x10;
         newContext->es = 0x10;
         newContext->cs = 0x8;
         newContext->ebp = (u32int)(proc->stackBase);
         newContext->esp = (u32int)(proc->stackTop);
         newContext->eip = (u32int)func;
         newContext->eflags = 0x202;
         addReadyAtEnd(proc);
     }
 }
void setAlarm ()
Procedure: setAlarm
Description: Sets an alarm based on the user provided time and prints the user provided message when the time has been reached.
Parameters: char* message – pointer to the alarm message char* time – the time the alarm will be set to (HH:MM:SS) Return: Void
Definition at line 652 of file command_handler.c.
References alarmFlag1, alarmFlag2, alarmFlag3, alarmFlag4, alarmMsg1, alarmMsg2, alarmMsg3, alarmMsg4, alarmTime1, alarmTime2, alarmTime3, atoi(), BCD_to_Dec(), DEFAULT_DEVICE, dontCall1, dontCall2, dontCall3, dontCall4, EXIT, date_time_char::hour, IDLE, inb, memset(), date_time_char::min, msg1, msg2, msg3, msg4, new_time_reader(), NULL, outb, RTC_BASE, RTC_HOUR, RTC_MINUTE, RTC_READ, RTC_SECOND, date_time_char::sec, strcat(), strcpy(), sys_req(), and WRITE.
                {
   unsigned char sec, min, hour;
   char currTime[100];
   int timeValue = 0;
     int exitFlag = 0;
     int userTime1 = 0;
     int userTime2 = 0;
     int userTime3 = 0;
     int userTime4 = 0;
     // char* msg = alarmMsg;
     // char* almTme = alarmTime;
     char* msg1;
     char* almTme1;
     char* msg2;
     char* almTme2;
     char* msg3;
     char* almTme3;
     char* msg4;
     char* almTme4;
   char msgBuff[100];
   int msgLength = 0;
   date_time_char* time_reader = new_time_reader();
   while(1){
     outb(RTC_BASE, RTC_SECOND);
     sec = inb(RTC_READ);
     outb(RTC_BASE, RTC_MINUTE);
     min = inb(RTC_READ);
     outb(RTC_BASE, RTC_HOUR);
     hour = inb(RTC_READ);
     BCD_to_Dec(hour, time_reader->hour);
     BCD_to_Dec(min, time_reader->min);
     BCD_to_Dec(sec, time_reader->sec);
     memset(currTime, '\0', sizeof(currTime));
     strcpy(currTime, time_reader->hour);
     strcat(currTime, time_reader->min);
     strcat(currTime, time_reader->sec);
     timeValue = atoi(currTime);
         msg1 = alarmMsg1;
         almTme1 = alarmTime1;
         msg2 = alarmMsg2;
         almTme2 = alarmTime2;
         msg3 = alarmMsg3;
         almTme3 = alarmTime3;
         msg4 = alarmMsg4;
         almTme4 = alarmMsg4;
         userTime1 = atoi(almTme1);
         userTime2 = atoi(almTme2);
         userTime3 = atoi(almTme3);
         userTime4 = atoi(almTme4);
         // serial_print("Current Time: ");
         // serial_println(currTime);
         // serial_print("User Time: ");
         // serial_println(almTme1);
     if(timeValue >= userTime1 && alarmFlag1 == 1 && dontCall1 != 1){
       memset(msgBuff, '\0', sizeof(msgBuff));
       strcpy(msgBuff, msg1);
       msgLength = sizeof(msgBuff);
       sys_req( WRITE, DEFAULT_DEVICE, msgBuff, &msgLength);
             // alarmFlag1 = 0;
             dontCall1 = 1;
             exitFlag = 1;
     }
         if(timeValue >= userTime2 && alarmFlag2 == 1 && dontCall2 != 1){
       memset(msgBuff, '\0', sizeof(msgBuff));
       strcpy(msgBuff, msg2);
       msgLength = sizeof(msgBuff);
       sys_req( WRITE, DEFAULT_DEVICE, msgBuff, &msgLength);
             // alarmFlag2 = 0;
             dontCall2 = 1;
             exitFlag = 1;
     }
         if(timeValue >= userTime3 && alarmFlag3 == 1 && dontCall3 != 1){
       memset(msgBuff, '\0', sizeof(msgBuff));
       strcpy(msgBuff, msg3);
       msgLength = sizeof(msgBuff);
       sys_req( WRITE, DEFAULT_DEVICE, msgBuff, &msgLength);
             // alarmFlag3 = 0;
             dontCall3 = 1;
             exitFlag = 1;
     }
         if(timeValue >= userTime4 && alarmFlag4 == 1 && dontCall4 != 1){
       memset(msgBuff, '\0', sizeof(msgBuff));
       strcpy(msgBuff, msg4);
       msgLength = sizeof(msgBuff);
       sys_req( WRITE, DEFAULT_DEVICE, msgBuff, &msgLength);
             // alarmFlag4 = 0;
             dontCall4 = 1;
             exitFlag = 1;
     }
         if(exitFlag == 1){
             exitFlag = 0;
             sys_req(EXIT, DEFAULT_DEVICE, NULL, NULL);
             return;
         }
         else{
             // serial_println("IDLING... ");
       sys_req(IDLE, DEFAULT_DEVICE, NULL, NULL);
     }
   }
 }
void shutdown ()
Procedure: shutdown
Description: Exits the command handler to kmain.c, thus begining system shutdown.
Parameters: None
Returns: Void
Definition at line 594 of file command_handler.c.
References quit.
                {
   quit = 1;
   return;
 }
void splashScreen ()
Procedure: splashScreen
Description: Displays the welcome screen for the operating system.
Parameters: None
Returns: Void
Definition at line 564 of file command_handler.c.
References count, DEFAULT_DEVICE, memset(), strcat(), strcpy(), strlen(), sys_req(), VERSION, and WRITE.
                    {
   int count = 0;
   char cmdBuffer[2300]; //min 2251 (added extra room)
   memset(cmdBuffer, '\0', sizeof(cmdBuffer));
   strcpy(cmdBuffer, "\n\n\n                #################################\n               #### Welcome to Knuckles OS! ####\n              #################################\n              VERSION: ");
   strcat(cmdBuffer, VERSION);
   strcat(cmdBuffer, "\n       AUTHORS: John Bowling\n              John Dando\n            Sebastian Reger\n            Kevin Shrader\n\n\n\n                \"I will be your guide.\"\n\n\n\n\n\n\n");
   count = strlen(cmdBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
 }
void version ()
Procedure: version
Description: Displays the current version of the operating system (Module and Revision).
Parameters: None
Returns: Void
Definition at line 575 of file command_handler.c.
References COMPLETE_DATE, count, DEFAULT_DEVICE, memset(), strcat(), strcpy(), strlen(), sys_req(), VERSION, and WRITE.
               {
   char cmdBuffer[30];
   int count = 0;
     memset( cmdBuffer, '\0', sizeof(cmdBuffer));
     strcpy(cmdBuffer, "Version: ");
     strcat(cmdBuffer, VERSION);
     strcat(cmdBuffer, "\n");
     count = strlen(cmdBuffer);
     sys_req(WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
     strcpy(cmdBuffer,"Completion Date: ");
     strcat(cmdBuffer, COMPLETE_DATE);
     strcat(cmdBuffer, "\n");
     count = strlen(cmdBuffer);
     sys_req(WRITE,DEFAULT_DEVICE, cmdBuffer, &count);
     return;
 }
Variable Documentation
int alarmFlag1 = 0
Definition at line 19 of file command_handler.c.
int alarmFlag2 = 0
Definition at line 20 of file command_handler.c.
int alarmFlag3 = 0
Definition at line 21 of file command_handler.c.
int alarmFlag4 = 0
Definition at line 22 of file command_handler.c.
char alarmMsg1[30]
Definition at line 12 of file command_handler.c.
char alarmMsg2[30]
Definition at line 14 of file command_handler.c.
char alarmMsg3[30]
Definition at line 16 of file command_handler.c.
char alarmMsg4[30]
Definition at line 18 of file command_handler.c.
char alarmTime1[10]
Definition at line 11 of file command_handler.c.
char alarmTime2[10]
Definition at line 13 of file command_handler.c.
char alarmTime3[10]
Definition at line 15 of file command_handler.c.
char alarmTime4[10]
Definition at line 17 of file command_handler.c.
int dontCall1 = 0
Definition at line 23 of file command_handler.c.
int dontCall2 = 0
Definition at line 24 of file command_handler.c.
int dontCall3 = 0
Definition at line 25 of file command_handler.c.
int dontCall4 = 0
Definition at line 26 of file command_handler.c.
char* history
Definition at line 10 of file command_handler.c.
int quit = 0
Definition at line 8 of file command_handler.c.