Knuckles OS: modules/error_handler.h File Reference
error_handler.h File Reference
Macros
#define E_NONE 0
#define E_PARAMS 1
#define E_FORMAT 2
#define E_UINPUT 3
#define E_NULL_PTR 4
#define E_EMPTPCB 5
#define E_PCB_CLASS 6
#define E_FREE_MEM 7
#define E_NOT_FOUND 8
#define E_STATE 9
#define E_EXISTS 10
#define E_HOUR 11
#define E_MIN 12
#define E_SEC 13
#define E_MONTH 14
#define E_DAY 15
#define E_YEAR 16
#define E_CMD 17
#define E_HELP 18
Typedefs
typedef int error_t
Functions
void errorHandler (error_t error)
Macro Definition Documentation
#define E_CMD 17
Definition at line 52 of file error_handler.h.
#define E_DAY 15
Definition at line 46 of file error_handler.h.
#define E_EMPTPCB 5
Definition at line 17 of file error_handler.h.
#define E_EXISTS 10
Definition at line 31 of file error_handler.h.
#define E_FORMAT 2
Definition at line 8 of file error_handler.h.
#define E_FREE_MEM 7
Definition at line 23 of file error_handler.h.
#define E_HELP 18
Definition at line 55 of file error_handler.h.
#define E_HOUR 11
Definition at line 34 of file error_handler.h.
#define E_MIN 12
Definition at line 37 of file error_handler.h.
#define E_MONTH 14
Definition at line 43 of file error_handler.h.
#define E_NONE 0
Definition at line 2 of file error_handler.h.
#define E_NOT_FOUND 8
Definition at line 26 of file error_handler.h.
#define E_NULL_PTR 4
Definition at line 14 of file error_handler.h.
#define E_PARAMS 1
Definition at line 5 of file error_handler.h.
#define E_PCB_CLASS 6
Definition at line 20 of file error_handler.h.
#define E_SEC 13
Definition at line 40 of file error_handler.h.
#define E_STATE 9
Definition at line 29 of file error_handler.h.
#define E_UINPUT 3
Definition at line 11 of file error_handler.h.
#define E_YEAR 16
Definition at line 49 of file error_handler.h.
Typedef Documentation
typedef int error_t
Definition at line 58 of file error_handler.h.
Function Documentation
void errorHandler (error_t error)
Definition at line 6 of file error_handler.c.
References count, DEFAULT_DEVICE, E_CMD, E_DAY, E_EMPTPCB, E_EXISTS, E_FORMAT, E_FREE_MEM, E_HELP, E_HOUR, E_MIN, E_MONTH, E_NONE, E_NOT_FOUND, E_NULL_PTR, E_PARAMS, E_PCB_CLASS, E_SEC, E_STATE, E_UINPUT, E_YEAR, memset(), strcpy(), strlen(), sys_req(), and WRITE.
{
     char errBuffer[100];
     int count;
     if(error == E_NONE) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E1: Success\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_PARAMS) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E2: Invalid Parameters. Type 'help command' for the usage of function 'command'\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_FORMAT) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E3: Invalid String Format. Type 'help command' for the usage of function 'command'\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_UINPUT) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E4: Invalid User Input\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_NULL_PTR) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E5: Null Pointer Exception\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_EMPTPCB) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E6: PCB Queue Empty\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_PCB_CLASS) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E7: Invalid Class\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_FREE_MEM) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E8: Failed to Free Memory\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_NOT_FOUND) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E9: Process Not Found\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_STATE) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E10: Process In State\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_EXISTS) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E11: Process Exists\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_HOUR) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E12: Invalid Hour for Time. Type 'help command' for the usage of function 'command'\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_MIN) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E13: Invalid Minute for Time. Type 'help command' for the usage of function 'command'\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_SEC) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E14: Invalid Second for Time. Type 'help command' for the usage of function 'command'\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_MONTH) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E15: Invalid Month for Date. Type 'help command' for the usage of function 'command'\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_DAY) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E16: Invalid Day for Date. Type 'help command' for the usage of function 'command'\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_YEAR) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E17: Invalid Year for Date. Type 'help command' for the usage of function 'command'\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_CMD) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E18: Invalid Command. Type 'help' for a list of commands\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if (error == E_HELP) {
         memset( errBuffer, '\0', sizeof(errBuffer));
             strcpy(errBuffer, "E19: Invalid Help Command. Type 'help' for a list of commands\n");
             count = strlen(errBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     return;
 }