Knuckles OS: modules/error_handler.c File Reference
error_handler.c File Reference
#include "mpx_supt.h"
#include "error_handler.h"
#include <string.h>
Functions
void errorHandler (error_t error)
Function Documentation
void errorHandler (error_t error)
Definition at line 6 of file error_handler.c.
References count, DEFAULT_DEVICE, E_EMPTPCB, E_FORMAT, E_FREE_MEM, E_NONE, E_NOT_FOUND, E_NULL_PTR, E_PARAMS, E_PCB_CLASS, E_STATE, E_UINPUT, memset(), strcpy(), strlen(), sys_req(), and WRITE.
{
     char errBuffer[100];
     int count;
     if(error == E_NONE) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E1: Success\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_PARAMS) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E2: Invalid Parameters. Type 'help command' for the usage of function 'command'\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_FORMAT) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E3: Invalid String Format\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_UINPUT) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E4: Invalid User Input\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_NULL_PTR) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E5: Null Pointer Exception\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_EMPTPCB) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E6: PCB Queue Empty\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_PCB_CLASS) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E7: Invalid Class\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_FREE_MEM) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E8: Failed to Free Memory\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_NOT_FOUND) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E9: Process Not Found\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     else if(error == E_STATE) {
         memset( errBuffer, '\0', sizeof(errBuffer));
     strcpy(errBuffer, "E10: Process In State\n");
     count = strlen(errBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, errBuffer, &count);
     }
     return;
 }