Knuckles OS: modules/help.c File Reference
help.c File Reference
#include "help.h"
#include "command_handler.h"
Functions
void generalHelp ()
void helpGetTime ()
void helpSetTime ()
void helpGetDate ()
void helpSetDate ()
void helpVersion ()
void helpQuit ()
void helpSuspend ()
void helpResume ()
void helpPriority ()
void helpShow ()
void helpShowAll ()
void helpShowReady ()
void helpShowBlocked ()
void helpCreate ()
void helpRemove ()
void helpBlock ()
void helpUnblock ()
void helpYield ()
void helpLoadr3 ()
void helpSetAlarm ()
Variables
int exit = 1
char helpBuffer [1200]
int count
Function Documentation
void generalHelp ()
Procedure: generalHelp
Description: Opens the help menu. Allows for user input for Knuckles OS commands. Provides a detailed description of each command.
Parameters: None
Returns: Void
Definition at line 8 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcat(), strcpy(), strlen(), sys_req(), VERSION, and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "Knuckles OS version: ");
     strcat(helpBuffer, VERSION);
     strcat(helpBuffer,"\n-knuckles: This is a list of all defined user commands. Type 'help name'\n to learn more about function 'name.'\n\n");
     strcat(helpBuffer, "gettime\t\t\t\tsettime\t\t\t\tgetdate\nsetdate\t\t\t\tversion\t\t\t\tquit\nsuspend\t\t\t\tresume\t\t\t\tpriority\nshow\t\t\t\tshowall\t\t\t\tshowready\nremove\t\t\t\tcreate\t\t\t\tshowblocked\nblock\t\t\t\tunblock\t\t\t\tsetalarm\nyield (R3 ONLY)\t\t\tloadr3 (R3 ONLY)\n");
     count = strlen(helpBuffer);
     sys_req(WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpBlock ()
Procedure: helpBlock
Description: Provides a detailed description of the block command.
Parameters: None
Return: Void
Definition at line 156 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                 {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "BLOCK:\nThis command searches for the Process Control Block (PCB) based on the\nuser provided process name, finds the queue the PCB is located in,\nchanges the PCB state to blocked, and places the PCB in the appropriate\nqueue.\n\nThe process name is any PCB name that has already been created. If the\nuser provides a name with less than 8 characters or a name of a PCB that\nis not located within a queue, then this will be considered invalid.\n\nIf the PCB state is already blocked, then a message will inform the\nuser of the current state of the PCB.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: block processName\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpCreate ()
Procedure: helpCreatePCB
Description: Provides a detailed description of the createpcb command.
Parameters: None
Returns: Void
Definition at line 138 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                  {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "CREATE PCB:\nThis command creates a Process Control Block (PCB) based upon the three\nparameters provided by the user: name, class, and priority. The command\nthen places the process in the appropriate queue for eventual execution.\n\nThe process name can be any unique combination of at least 8 characters.\n\nThe process class is an integer that defines the process as either an\napplication or a system process. The class can be either a 0 for system\nprocess or a 1 for application process.\n\nThe process priorty is the importance of the process. Processes with lower\npriorty will execute after high priorty processes. The priorty can be any\ninteger between 0 and 9 with 0 being the highest priorty and 9 being the\nlowest.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: create processName class priorityNumber\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpGetDate ()
Procedure: helpGetDate
Description: Provides a detailed description of the getdate command.
Parameters: None
Returns: Void
Definition at line 39 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "GET DATE:\nThis command allows the user to see the current date that is programmed into\nKnuckles OS.\n\nUsage: MM\\DD\\YY\n\"MM\" is a month\n\"DD\" is a day\n\"YY\" is a year (for now years are locked in the 2000s).\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpGetTime ()
Procedure: helpGetTime
Description: Provides a detailed description of the gettime command.
Parameters: None
Returns: Void
Definition at line 21 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "GET TIME:\nThis command allows the user to see the current time that is programmed into \nKnuckles OS.\n\nUsage: HH:MM:SS\n\"HH\" is an hour from 0-23\n\"MM\" is a minute from 0 to 59\n\"SS\" is a second from 0 to 59\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpLoadr3 ()
Procedure: helpLoadr3
Description: Provides a detailed desctiption of the loadr3 command.
Parameters: None
Return: Void
Definition at line 183 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                   {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "LOADR3:\nThis command loads all provided processes (five) into memory as \na part of the PCB Queues in the suspended ready state.\n\nUsage: loadr3\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpPriority ()
Procedure: helpSetPriorty
Description: Provides a detailed description of the setpriorty command.
Parameters: None
Returns: Void
Definition at line 93 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SET PRIORTY:\nBased on the parameters given by the user, this command changes the\npriorty value of the Process Control Block (PCB), removes the PCB\nfrom its current place in its current queue, and reinserts the PCB\nin the correct position within the correct queue.\n\nThis command takes two parameters: name and priorty.\n\nThe process name is any PCB name that has already been created. If the\nuser provides a name with less than 8 characters or a name of a PCB that\nis not located within a queue, then this will be considered invalid.\n\nThe process priorty is the importance of the process. Processes with lower\npriorty will execute after high priorty processes. The priorty can be any\ninteger between 0 and 9 with 0 being the highest priorty and 9 being the\nlowest.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: priority processName priorityNumber\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpQuit ()
Procedure: helpQuit
Description: Provides a detailed description of the quit command.
Parameters: None
Returns: Void
Definition at line 66 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                 {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "QUIT:\nThis command begins the exit sequence of the command handler and returns\nto the terminal.\n\nA prompt will ask whether or not the user would like to continue with shutdown.\nThe user will either select Y/y for 'yes' or N/n for 'no'.\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpRemove ()
Procedure: helpDeletePCB
Description: Provides a detailed description of the deletepcb command.
Parameters: None
Returns: Void
Definition at line 147 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                  {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "DELETE PCB:\nThis command searches for the Process Control Block (PCB) based on the\nuser provided process name, finds the queue the PCB is located in, and\nremoves the PCB from that queue.\n\nThe process name is any PCB name that has already been created. If the\nuser provides a name with less than 8 characters or a name of a PCB that\nis not located within a queue, then this will be considered invalid.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: remove processName\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpResume ()
Procedure: helpResume
Description: Provides a detailed description of the resume command.
Parameters: None
Returns: Void
Definition at line 84 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                  { //What is the not suspended state
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "RESUME:\nThis command searches for the Process Control Block (PCB) based on the\nuser provided process name, finds the queue the PCB is located in,\nchanges the PCB to an unsuspended state, and places the PCB in the\nappropriate queue.\n\nThe process name is any PCB name that has already been created. If the\nuser provides a name with less than 8 characters or a name of a PCB that\nis not located within a queue, then this will be considered invalid.\n\nIf the PCB state is already unsuspended, then a message will inform the\nuser of the current state of the PCB.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: resume processName\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpSetAlarm ()
Procedure: helpSetAlarm
Description: Provides a detailed description of the setalarm command.
Parameters: None
Return: Void
Definition at line 192 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                     {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
     count = 0;
     strcpy(helpBuffer, "SET ALARM:\nThis command allows the user to set a time specific alarm and displays a\nuser created message. The command takes two parameters: a specific time and a\nmessage.\n\nThe time parameter can be any valid time written in the following format:\nHH MM SS where \"HH\" is an hour from 0-23,\"MM\" is a minute from 0 to 59,\n\"SS\" is a second from 0 to 59.\n\nThe user-specified message can be any combination of characters greater\n\nthan zero and less than one hundred. Any invalid parameter will result in \nan error, and the user must enter the command and parameters again correctly.\n\nUsage: setalarm 12 23 34 This is an alarm.\n");
     count = strlen(helpBuffer);
     sys_req(WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpSetDate ()
Procedure: helpSetData
Description: Provides a detailed description of the setdate command.
Parameters: None
Returns: Void
Definition at line 48 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SET DATE:\nThis command allows the user to adjust the date.\n\nThe user would set the desired month, day, and year for the date.\n\nUsage: 'setdate MM DD YY'\n\"MM\" is a month\n\"DD\" is a day\n\"YY\" is a year (for now years are locked in the 2000s).\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpSetTime ()
Procedure: helpSetTime
Description: Provides a detailed description of the settime command.
Parameters: None
Returns: Void
Definition at line 30 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SET TIME:\nThis command allows the user to adjust the time of the virtual clock.\n\nThe user would set the desired hour, minute, and second for the clock.\n\nUsage: 'settime HH MM SS'\n\"HH\" is an hour from 0-23\n\"MM\" is a minute from 0 to 59\n\"SS\" is a second from 0 to 59\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpShow ()
Procedure: helpShowPCB
Description: Provides a detailed description of the showpcb command.
Parameters: None
Returns: Void
Definition at line 102 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SHOW PCB:\nThis command displays the following Process Control Block (PCB)\ninformation based on the PCB name provided by the user: name, class,\nstate, suspended status, and priorty.\n\n1 - The name is the given identifier that has been provided for the PCB.\n    As a parameter for the command, it must be any PCB name that has\n    already been created. If the user provides a name with less than 8\n    characters or a name of a PCB that is not located within a queue,\n    then this will be considered invalid.\n2 - The process class is an integer that defines the process as either an\n    application or a system process.\n3 - The state is the determination if the the PCB is either ready, running,\n    or blocked.\n4 - The suspension status shows whether the PCB is suspended or not.\n5 - The process priorty is the importance of the process. Processes with lower\n    priorty will execute after high priorty processes. The priorty can be any\n    integer between 0 and 9 with 0 being the lowest priorty and 9 being the\n    highest.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: show processName\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpShowAll ()
Procedure: helpShowAll
Description: Provides a detailed description of the showall command.
Parameters: None
Returns: Void
Definition at line 111 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                   {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SHOW ALL:\nThis command displays the following Process Control Block (PCB)\ninformation for each PCB located within each queue: name, class,\nstate, suspended status, and priorty.\n\n1 - The name is the given identifier that has been provided for the PCB.\n2 - The process class is an integer that defines the process as either an\n    application or a system process.\n3 - The state is the determination if the the PCB is either ready, running,\n    or blocked.\n4 - The suspension status shows whether the PCB is suspended or not.\n5 - The process priorty is the importance of the process. Processes with lower\n    priorty will execute after high priorty processes. The priorty can be any\n    integer between 0 and 9 with 0 being the highest priorty and 9 being the\n    lowest.\n\nUsage: showall\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpShowBlocked ()
Procedure: helpShowBlocked
Description: Provides a detailed description of the showblocked command.
Parameters: None
Returns: Void
Definition at line 129 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                       {//depends on 2 or 4 queue format
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SHOW BLOCKED:\nThis command displays the following Process Control Block (PCB)\ninformation for each PCB located within the blocked queue: name, class,\nstate, suspended status, and priorty.\n\n1 - The name is the given identifier that has been provided for the PCB.\n2 - The process class is an integer that defines the process as either an\n    application or a system process.\n3 - The state is the determination if the the PCB is either ready, running,\n    or blocked.\n4 - The suspension status shows whether the PCB is suspended or not.\n5 - The process priorty is the importance of the process. Processes with lower\n    priorty will execute after high priorty processes. The priorty can be any\n    integer between 0 and 9 with 0 being the highest priorty and 9 being the\n    lowest.\n\nUsage: showblocked\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpShowReady ()
Procedure: helpShowReady
Description: Provides a detailed description of the showready command.
Parameters: None
Returns: Void
Definition at line 120 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                     {//depends on 2 or 4 queue format
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "SHOW READY:\nThis command displays the following Process Control Block (PCB)\ninformation for each PCB located within the ready queue: name, class,\nstate, suspended status, and priorty.\n\n1 - The name is the given identifier that has been provided for the PCB.\n2 - The process class is an integer that defines the process as either an\n    application or a system process.\n3 - The state is the determination if the the PCB is either ready, running,\n    or blocked.\n4 - The suspension status shows whether the PCB is suspended or not.\n5 - The process priorty is the importance of the process. Processes with lower\n    priorty will execute after high priorty processes. The priorty can be any\n    integer between 0 and 9 with 0 being the highest priorty and 9 being the\n    lowest.\n\nUsage: showready\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpSuspend ()
Procedure: helpSuspend
Description: Provides a detailed description of the suspend command.
Parameters: None
Returns: Void
Definition at line 75 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                   {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "SUSPEND:\nThis command searches for the Process Control Block (PCB) based on the\nuser provided process name, finds the queue the PCB is located in,\nchanges the PCB state to suspended, and places the PCB in the appropriate\nqueue.\n\nThe process name is any PCB name that has already been created. If the\nuser provides a name with less than 8 characters or a name of a PCB that\nis not located within a queue, then this will be considered invalid.\n\nIf the PCB state is already suspended, then a message will inform the\nuser of the current state of the PCB.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: suspend processName\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpUnblock ()
Procedure: helpUnblock
Description: Provides a detailed description of the unblock command.
Parameters: None
Return: Void
Definition at line 165 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                   {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "UNBLOCK:\nThis command searches for the Process Control Block (PCB) based on the\nuser provided process name, finds the queue the PCB is located in,\nchanges the PCB state to unblocked, and places the PCB in the appropriate\nqueue.\n\nThe process name is any PCB name that has already been created. If the\nuser provides a name with less than 8 characters or a name of a PCB that\nis not located within a queue, then this will be considered invalid.\n\nIf the PCB state is already unblocked, then a message will inform the\nuser of the current state of the PCB.\n\nAny invalid parameter will result in an error, and the user must enter the \ncommand and parameters again correctly.\n\nUsage: unblock processName\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpVersion ()
Procedure: helpVersion
Description: Provides a detailed description of the version command.
Parameters: None
Returns: Void
Definition at line 57 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                    {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
   strcpy(helpBuffer, "VERSION:\nThis command shows the current version of Knuckles OS\nand the completion date of that version.\n");
   count = strlen(helpBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
void helpYield ()
Procedure: helpYield
Description: Provides a detailed description of the yield command.
Parameters: None
Return: Void
Definition at line 174 of file help.c.
References count, DEFAULT_DEVICE, helpBuffer, memset(), strcpy(), strlen(), sys_req(), and WRITE.
                  {
     memset( helpBuffer, '\0', sizeof(helpBuffer));
   count = 0;
     strcpy(helpBuffer, "YIELD:\nThis command pauses the command handler and executes\nall processes. It is when all processes are complete that the \ncommand handler regains control.\n\nUsage: yield\n");
     count = strlen(helpBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, helpBuffer, &count);
     return;
 }
Variable Documentation
int count
Definition at line 6 of file help.c.
int exit = 1
Definition at line 4 of file help.c.
char helpBuffer[1200]
Definition at line 5 of file help.c.