Knuckles OS: kernel/core/interrupts.c File Reference
interrupts.c File Reference
#include <system.h>
#include <core/io.h>
#include <core/serial.h>
#include <core/tables.h>
#include <core/interrupts.h>
#include <modules/mpx_supt.h>
#include "modules/R2/queue_commands.h"
Macros
#define PIC1 0x20
#define PIC2 0xA0
#define ICW1 0x11
#define ICW4 0x01
#define io_wait() asm volatile ("outb $0x80")
Functions
void divide_error ()
void debug ()
void nmi ()
void breakpoint ()
void overflow ()
void bounds ()
void invalid_op ()
void device_not_available ()
void double_fault ()
void coprocessor_segment ()
void invalid_tss ()
void segment_not_present ()
void stack_segment ()
void general_protection ()
void page_fault ()
void reserved ()
void coprocessor ()
void rtc_isr ()
void sys_call_isr ()
void isr0 ()
void do_isr ()
void init_irq (void)
void init_pic (void)
void do_divide_error ()
void do_debug ()
void do_nmi ()
void do_breakpoint ()
void do_overflow ()
void do_bounds ()
void do_invalid_op ()
void do_device_not_available ()
void do_double_fault ()
void do_coprocessor_segment ()
void do_invalid_tss ()
void do_segment_not_present ()
void do_stack_segment ()
void do_general_protection ()
void do_page_fault ()
void do_reserved ()
void do_coprocessor ()
void cop_print ()
u32int * sys_call (Context *registers)
Variables
PCB * cop = NULL
Context * copContext
param params
idt_entry idt_entries [256]
Macro Definition Documentation
#define ICW1 0x11
Definition at line 23 of file interrupts.c.
#define ICW4 0x01
Definition at line 24 of file interrupts.c.
#define io_wait () asm volatile ("outb $0x80")
Definition at line 36 of file interrupts.c.
#define PIC1 0x20
Definition at line 19 of file interrupts.c.
#define PIC2 0xA0
Definition at line 20 of file interrupts.c.
Function Documentation
void bounds ()
void breakpoint ()
void cop_print ()
Definition at line 210 of file interrupts.c.
References serial_println().
                  {
     serial_println("COP set");
 }
void coprocessor ()
void coprocessor_segment ()
void debug ()
void device_not_available ()
void divide_error ()
void do_bounds ()
Definition at line 162 of file interrupts.c.
References kpanic().
 {
   kpanic("Bounds error");
 }
void do_breakpoint ()
Definition at line 154 of file interrupts.c.
References kpanic().
 {
   kpanic("Breakpoint");
 }
void do_coprocessor ()
Definition at line 206 of file interrupts.c.
References kpanic().
 {
   kpanic("Coprocessor error");
 }
void do_coprocessor_segment ()
Definition at line 178 of file interrupts.c.
References kpanic().
 {
   kpanic("Coprocessor segment error");
 }
void do_debug ()
Definition at line 146 of file interrupts.c.
References kpanic().
 {
   kpanic("Debug");
 }
void do_device_not_available ()
Definition at line 170 of file interrupts.c.
References kpanic().
 {
   kpanic("Device not available");
 }
void do_divide_error ()
Definition at line 142 of file interrupts.c.
References kpanic().
 {
   kpanic("Division-by-zero");
 }
void do_double_fault ()
Definition at line 174 of file interrupts.c.
References kpanic().
 {
   kpanic("Double fault");
 }
void do_general_protection ()
Definition at line 194 of file interrupts.c.
References kpanic().
 {
   kpanic("General protection fault");
 }
void do_invalid_op ()
Definition at line 166 of file interrupts.c.
References kpanic().
 {
   kpanic("Invalid operation");
 }
void do_invalid_tss ()
Definition at line 182 of file interrupts.c.
References kpanic().
 {
   kpanic("Invalid TSS");
 }
void do_isr ()
Definition at line 62 of file interrupts.c.
References COM2, inb, outb, serial_print(), and serial_println().
 {
   char in = inb(COM2);
   serial_print(&in);
   serial_println("here");
   outb(0x20,0x20); //EOI
 }
void do_nmi ()
Definition at line 150 of file interrupts.c.
References kpanic().
 {
   kpanic("NMI");
 }
void do_overflow ()
Definition at line 158 of file interrupts.c.
References kpanic().
 {
   kpanic("Overflow error");
 }
void do_page_fault ()
Definition at line 198 of file interrupts.c.
References kpanic().
 {
   kpanic("Page Fault");
 }
void do_reserved ()
Definition at line 202 of file interrupts.c.
References serial_println().
 {
   serial_println("die: reserved");
 }
void do_segment_not_present ()
Definition at line 186 of file interrupts.c.
References kpanic().
 {
   kpanic("Segment not present");
 }
void do_stack_segment ()
Definition at line 190 of file interrupts.c.
References kpanic().
 {
   kpanic("Stack segment error");
 }
void double_fault ()
void general_protection ()
void init_irq (void)
Definition at line 75 of file interrupts.c.
References bounds(), breakpoint(), coprocessor(), coprocessor_segment(), debug(), device_not_available(), divide_error(), double_fault(), general_protection(), idt_set_gate(), invalid_op(), invalid_tss(), nmi(), overflow(), page_fault(), reserved(), rtc_isr(), segment_not_present(), stack_segment(), and sys_call_isr().
 {
   int i;
   // Necessary interrupt handlers for protected mode
   u32int isrs[17] = {
     (u32int)divide_error,
     (u32int)debug,
     (u32int)nmi,
     (u32int)breakpoint,
     (u32int)overflow,
     (u32int)bounds,
     (u32int)invalid_op,
     (u32int)device_not_available,
     (u32int)double_fault,
     (u32int)coprocessor_segment,
     (u32int)invalid_tss,
     (u32int)segment_not_present,
     (u32int)stack_segment,
     (u32int)general_protection,
     (u32int)page_fault,
     (u32int)reserved,
     (u32int)coprocessor
   };
   // Install handlers; 0x08=sel, 0x8e=flags
   for(i=0; i<32; i++){
     if (i<17) idt_set_gate(i, isrs[i], 0x08, 0x8e);
     else idt_set_gate(i, (u32int)reserved, 0x08, 0x8e);
   }
   // Ignore interrupts from the real time clock
   idt_set_gate(0x08, (u32int)rtc_isr, 0x08, 0x8e);
     idt_set_gate(60, (u32int)sys_call_isr, 0x08, 0x8e);
 }
void init_pic (void)
Definition at line 119 of file interrupts.c.
References ICW1, ICW4, io_wait, outb, PIC1, and PIC2.
 {
   outb(PIC1,ICW1);   //send initialization code words 1 to PIC1
   io_wait();
   outb(PIC2,ICW1);   //send icw1 to PIC2
   io_wait();
   outb(PIC1+1,0x20); //icw2: remap irq0 to 32
   io_wait();
   outb(PIC2+1,0x28); //icw2: remap irq8 to 40
   io_wait();
   outb(PIC1+1,4);    //icw3
   io_wait();
   outb(PIC2+1,2);    //icw3
   io_wait();
   outb(PIC1+1,ICW4); //icw4: 80x86, automatic handling
   io_wait();
   outb(PIC2+1,ICW4); //icw4: 80x86, automatic handling
   io_wait();
   outb(PIC1+1,0xFF); //disable irqs for PIC1
   io_wait();
   outb(PIC2+1,0xFF); //disable irqs for PIC2
 }
void invalid_op ()
void invalid_tss ()
void isr0 ()
void nmi ()
void overflow ()
void page_fault ()
void reserved ()
void rtc_isr ()
void segment_not_present ()
void stack_segment ()
u32int* sys_call (Context * registers)
Procedure: sys_call
Description: Executes Context switching
Parameters: Context* registers – Context of new process
Returns: Context of the new process
Definition at line 223 of file interrupts.c.
References changeState(), copContext, EXIT, FreePCB(), IDLE, InsertPCB(), NULL, param::op_code, peekReady(), popReady(), ready, running, and pcb::stackTop.
{
   if (cop == NULL) {
     copContext = registers;
   }
   else {
     if (params.op_code == IDLE) {
       cop->stackTop = (u32int*)registers;
             changeState(cop, ready);
       InsertPCB(cop);
     }
     else if (params.op_code == EXIT) {
       FreePCB(cop);
     }
   }
   if (peekReady() != NULL) {
         // serial_println("ready queue NOT empty");
     cop = popReady();
         changeState(cop, running);
     return cop->stackTop;
   } else {
         // serial_println("ready queue empty");
     return (u32int*)copContext;
   }
 }
void sys_call_isr ()
Variable Documentation
PCB* cop = NULL
Definition at line 26 of file interrupts.c.
Context* copContext
Definition at line 27 of file interrupts.c.
idt_entry idt_entries[256]
Definition at line 17 of file tables.c.
param params
Definition at line 15 of file mpx_supt.c.