Knuckles OS: kernel/core/kmain.c File Reference
kmain.c File Reference
#include <stdint.h>
#include <string.h>
#include <system.h>
#include <core/io.h>
#include <core/serial.h>
#include <core/tables.h>
#include <core/interrupts.h>
#include <mem/heap.h>
#include <mem/paging.h>
#include "modules/mpx_supt.h"
#include "modules/polling.h"
#include "modules/command_handler.h"
Macros
#define COM1 0x3f8
Functions
void kmain (void)
Macro Definition Documentation
#define COM1 0x3f8
Definition at line 25 of file kmain.c.
Function Documentation
void kmain (void)
Definition at line 27 of file kmain.c.
References COM1, com_handler(), hlt, idleProc(), init_gdt(), init_idt(), init_irq(), init_paging(), init_pic(), init_serial(), klogv(), loadToPCB(), MODULE_R4, mpx_init(), polling(), set_serial_in(), set_serial_out(), setupQueues(), sti, sys_set_read(), and system_process.
 {
    extern uint32_t magic;
    // Uncomment if you want to access the multiboot header
    // extern void *mbd;
    // char *boot_loader_name = (char*)((long*)mbd)[16];
    // 0) Initialize Serial I/O and call mpx_init
    init_serial(COM1);
    set_serial_out(COM1);
    set_serial_in(COM1);
    klogv("Starting MPX boot sequence...");
    klogv("Initialized serial I/O on COM1 device...");
    // 1) Initialize the support software by identifying the current
    //     MPX Module.  This will change with each module.
    mpx_init(MODULE_R4);
    // 2) Check that the boot was successful and correct when using grub
    // Comment this when booting the kernel directly using QEMU, etc.
    if ( magic != 0x2BADB002 ){
      //kpanic("Boot was not error free. Halting.");
    }
    // 3) Descriptor Tables
    klogv("Initializing descriptor tables...");
    init_idt(); // Interrupt Descriptor Table
    init_gdt(); // Global Descriptor Table
    init_pic(); // Programmable Interrupt Controllers
    init_irq(); // Interrupt Handlers
    sti(); // Enable interrupts
    // 4) Virtual Memory
    klogv("Initializing virtual memory...");
    init_paging();
    // char *buf;
    // int *count = 0;
    sys_set_read(&polling);
     //5) Setting the ready and blocked queues
     klogv("Initializing process queues...");
     setupQueues();
    // 6) Call YOUR command handler -  interface method
    klogv("Transferring control to command handler...");
    //com_handler();
     loadToPCB("commandhand", system_process, 0, com_handler);
     loadToPCB("idle", system_process, 9, idleProc);
     // loadR3();
      asm volatile ("int $60");
    // 7) System Shutdown on return from your command handler
    klogv("Starting system shutdown procedure...");
    /* Shutdown Procedure */
    klogv("Shutdown complete. You may now turn off the machine. (QEMU: C-a x)");
    hlt();
 }