Knuckles OS: modules/R5/memory_lists.c File Reference
memory_lists.c File Reference
#include "modules/R5/memory_lists.h"
Functions
void setupList ()
int setupHeap (int heap_size)
int lengthFree ()
int lengthAllocated ()
u32int allocate (u32int size)
int freeMemory (u32int address)
int insertCMCB (CMCB *cmcb, List *list)
int removeCMCB (CMCB *cmcb, List *list)
int mergeAdjacent (CMCB *cmcb)
u32int unsignedDiff (u32int a, int b)
List * getFreeList ()
List * getAllocatedList ()
Variables
char showBuffer [200]
unsigned int counter = 0
int count
int availableMemory
u32int heapStart = 0
Function Documentation
u32int allocate (u32int size)
Procedure: allocate
Description: Allocates memory from the heap based on the first fit method and moves the memory block into the allocate list
Parameters: u32int size – the number of bytes that will be allocated for a memory block
Return: u32int – error code (-1 if error occurs, 0 if successful)
Definition at line 55 of file memory_lists.c.
References allocatedBlock, cmcb::beginningAddress, count, DEFAULT_DEVICE, list::head, insertCMCB(), cmcb::memory_type, memset(), cmcb::next, NULL, removeCMCB(), showBuffer, cmcb::size, strcpy(), strlen(), sys_req(), unsignedDiff(), and WRITE.
{
     CMCB* cmcb;
     if(size % 4 != 0)
         size = (size & 0xFFFFFFFC) + 4;
     else
         size = size & 0xFFFFFFFC;
 // = (CMCB*)kmalloc(size + sizeof(CMCB));
     int error = 0;
     if(freeList.head == NULL)
         error = -1;
     else {
         CMCB* current = freeList.head;
         while(size > current->size && current->next != NULL) {
             current = current->next;
         }
         if(size + 28 >= current->size) {    // cmcb block too large for free blocks
             error = -1;
             memset( showBuffer, '\0', sizeof(showBuffer));
             strcpy(showBuffer, "Allocation too large!\n");
             count = strlen(showBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
         }
         else if(size >= unsignedDiff(current->size, sizeof(CMCB))) {
             current->memory_type = allocatedBlock;
             removeCMCB(current, &freeList);
             insertCMCB(current, &allocatedList);
         }
         else {
             CMCB* nextCMCB = (CMCB*)((void*)current + size + sizeof(CMCB));
             nextCMCB->beginningAddress = current->beginningAddress + sizeof(CMCB) + size;
             nextCMCB->size = current->size - size - sizeof(CMCB);
             cmcb = (CMCB*)(current);
             cmcb->memory_type = allocatedBlock;
             cmcb->beginningAddress = current->beginningAddress;
             cmcb->blockPtr = cmcb->beginningAddress + sizeof(CMCB);
             cmcb->size = size;
             removeCMCB(cmcb, &freeList);
             insertCMCB(nextCMCB, &freeList);
             insertCMCB(cmcb, &allocatedList);
         }
     }
     return error;
 }
int freeMemory (u32int address)
Procedure: freeMemory
Description: Frees a particular CMCB that has been previously allocated and moves the CMCB to the free list
Parameters: u32int address – address location for memory block that will be freed.
Return: int – error code (-1 if error occurs, 0 if successful)
Definition at line 105 of file memory_lists.c.
References cmcb::beginningAddress, count, DEFAULT_DEVICE, freeBlock, list::head, heapStart, cmcb::memory_type, memset(), mergeAdjacent(), cmcb::next, NULL, removeCMCB(), showBuffer, strcpy(), strlen(), sys_req(), and WRITE.
{
     int error = 0;
     if(allocatedList.head == NULL) {
         error = -1;
         memset( showBuffer, '\0', sizeof(showBuffer));
         strcpy(showBuffer, "List not defined.\n");
         count = strlen(showBuffer);
         sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     }
     else {
         CMCB* current = allocatedList.head;
         while(current->next != NULL && current->beginningAddress + sizeof(CMCB) - heapStart < address) {
             current = current->next;
         }
         if(current->beginningAddress + sizeof(CMCB) - heapStart == address) {
             current->memory_type = freeBlock;
           removeCMCB(current, &allocatedList);
             //insertCMCB(current, &freeList);
             memset( showBuffer, '\0', sizeof(showBuffer));
             strcpy(showBuffer, "Freed.\n");
             count = strlen(showBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
             mergeAdjacent(current);
         }
         else {
             memset( showBuffer, '\0', sizeof(showBuffer));
             strcpy(showBuffer, "Not Freed.\n");
             count = strlen(showBuffer);
             sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
             error = -1;
         }
     }
     return error;
 }
List* getAllocatedList ()
Procedure: getAllocatedList
Description: Returns a pointer to the Allocated List
Parameters: None
Return: List* – Pointer to the Allocated List
Definition at line 299 of file memory_lists.c.
{
     return &allocatedList;
 }
List* getFreeList ()
Procedure: getFreeList
Description: Returns a pointer to the Free List
Parameters: None
Return: List* – Pointer to the Free List
Definition at line 295 of file memory_lists.c.
                    {
     return &freeList;
 }
int insertCMCB (CMCB * cmcb, List * list)
Procedure: insertCMCB
Description: Inserts the input cmcb to its appropriate list.
Parameters: CMCB* cmcb – pointer to the CMCB that will be inserted into a particular list List* list – pointer to the list that the CMCB will be inserted into
Return: int – error code (-1 if error occurs, 0 if successful)
Definition at line 143 of file memory_lists.c.
References cmcb::beginningAddress, list::count, list::head, cmcb::next, NULL, cmcb::previous, and list::tail.
{
     int error = 0;
     CMCB* current = list->head;
     if(list->count == 0) {
         cmcb->next = NULL;
         cmcb->previous = NULL;
         list->head = cmcb;
         list->tail = cmcb;
     }
     else {
         while(current->next != NULL && current->beginningAddress < cmcb->beginningAddress) {
             current = current->next;
         }
         if(cmcb->beginningAddress < current->beginningAddress) {
             cmcb->next = current;
             cmcb->previous = current->previous;
             if(current->previous != NULL) {
                 cmcb->previous->next = cmcb;
             }
             current->previous = cmcb;
         }
         else {
             cmcb->next = NULL;
             cmcb->previous = current;
             current->next = cmcb;
         }
     }
     if(cmcb->previous == NULL) {
         list->head = cmcb;
     }
     if(cmcb->next == NULL) {
         list->tail = cmcb;
     }
     list->count++;
     return error;
 }
int lengthAllocated ()
Procedure: lengthAllocated
Description: Returns the length of the allocated list
Parameters: None
Return: int –length of the allocated list
Definition at line 49 of file memory_lists.c.
References list::count.
                       {
     return allocatedList.count;
 }
int lengthFree ()
Procedure: lengthFree
Description: Returns the length of the free list
Parameters: None
Return: int –length of the free list
Definition at line 45 of file memory_lists.c.
References list::count.
                  {
     return freeList.count;
 }
int mergeAdjacent (CMCB * cmcb)
Procedure: mergeAdjacent
Description: Merges free CMCB with adjacent CMCB if that particular CMCB is also free
Parameters: CMCB* cmcb – pointer to the complete memory control block that will be merged with adjacent free memory block
Return: int – error code (-1 if error occurs, 0 if successful)
Definition at line 219 of file memory_lists.c.
References cmcb::beginningAddress, list::head, insertCMCB(), cmcb::next, NULL, cmcb::previous, removeCMCB(), and cmcb::size.
{
     int error = 0;
         CMCB* current = freeList.head;
         while(current->next != NULL && current->beginningAddress < cmcb->beginningAddress) {
             current = current->next;
         }
         if(current->previous && cmcb->beginningAddress == current->previous->beginningAddress + current->previous->size + sizeof(CMCB)) {  // previous
             current->previous->size = current->previous->size + cmcb->size + sizeof(CMCB);
             if(current->previous->beginningAddress + current->previous->size + sizeof(CMCB) == current->beginningAddress) {
                 current->previous->size = current->previous->size + current->size + sizeof(CMCB);
                 removeCMCB(current, &freeList);
             }
         }
         else if(cmcb->beginningAddress + cmcb->size + sizeof(CMCB) == current->beginningAddress) {  // next
             cmcb->size = cmcb->size + current->size + sizeof(CMCB);
             removeCMCB(current, &freeList);
             insertCMCB(cmcb, &freeList);
             //if(current->previous && cmcb->beginningAddress == current->previous->beginningAddress + current->previous->size + sizeof(CMCB)) {
             //  current->previous->size = current->previous->size + cmcb->size + sizeof(CMCB);
             //}
         }
         else
             insertCMCB(cmcb, &freeList);
     return error;
 }
int removeCMCB (CMCB * cmcb, List * list)
Procedure: removeCMCB
Description: Removes the input cmcb from its appropriate list.
Parameters: CMCB* cmcb – pointer to the CMCB that will be removed from a particular list List* list – pointer to the list that the CMCB will be removed from
Return: int – error code (-1 if error occurs, 0 if successful)
Definition at line 182 of file memory_lists.c.
References cmcb::beginningAddress, list::count, list::head, cmcb::next, NULL, cmcb::previous, and list::tail.
{
     int error = 0;
     CMCB* current = list->head;
     if(list->count == 0) {
         error = -1;
     }
     else if(list->count == 1) {
         list->head = NULL;
         list->tail = NULL;
     }
     else {
         while(current->next != NULL && current->beginningAddress < cmcb->beginningAddress) {
             current = current->next;
         }
         if(current->beginningAddress == cmcb->beginningAddress) {
             if(current->next != NULL)   {   // Not located at tail
                 current->next->previous = current->previous;
             }
             else {
                 list->tail = current->previous;
             }
             if(current->previous != NULL) { // Not located at head
                 current->previous->next = current->next;
             }
             else {
                 list->head = current->next;
             }
         }
         else {
             error = -1;
         }
     }
     list->count--;
     return error;
 }
int setupHeap (int heap_size)
Procedure: setupHeap
Description: Calls setupList, initilizes the heap, and assigns its attributes default values
Parameters: int heap_size – the number of bytes that will be allocated for the heap
Return: int – error code (-1 if error occurs) OR heap_size – the number of bytes that will be allocated for the heap
Definition at line 22 of file memory_lists.c.
References availableMemory, freeBlock, heapStart, insertCMCB(), kmalloc(), NULL, and setupList().
{
     setupList();
     availableMemory = heap_size + sizeof(CMCB);
     CMCB* heap = (CMCB*)kmalloc(availableMemory);
     heap->memory_type = freeBlock;
     heap->beginningAddress = (u32int)heap;
     heap->blockPtr = heap->beginningAddress + sizeof(CMCB);
     heapStart = heap->blockPtr;
     heap->size = (u32int)heap_size;
     heap->name = "heap";
     heap->next = NULL;
     heap->previous = NULL;
     insertCMCB(heap, &freeList);
     if(heap != NULL){
     return heap_size;
   }
   else{
     return -1;
   }
 }
void setupList ()
Procedure: setupList
Description: Initializes the global lists (allocated and free) and assigns their attributes default values
Parameters: None
Return: Void
Definition at line 12 of file memory_lists.c.
References list::count, list::head, NULL, and list::tail.
                  {
     freeList.count = 0;
     freeList.head = NULL;
     freeList.tail = NULL;
     allocatedList.count = 0;
     allocatedList.head = NULL;
     allocatedList.tail = NULL;
 }
u32int unsignedDiff (u32int a, int b)
Procedure: unsignedDiff
Description: Returns the difference between an unsigned and integer value
Parameters: u32int a – value 1 int b – value 2
Returns: Positive difference between a and b
Definition at line 287 of file memory_lists.c.
{
     if(a > (u32int)b) {
         return a - (u32int)b;
     }
     else
         return 0;
 }
Variable Documentation
int availableMemory
Definition at line 9 of file memory_lists.c.
int count
Definition at line 6 of file memory_lists.c.
unsigned int counter = 0
Definition at line 5 of file memory_lists.c.
u32int heapStart = 0
Definition at line 10 of file memory_lists.c.
char showBuffer[200]
Definition at line 4 of file memory_lists.c.