Knuckles OS: modules/R5/memory_commands.c File Reference
memory_commands.c File Reference
#include "modules/R5/memory_commands.h"
Functions
int initializeHeap (int size)
int allocateMem (u32int memory)
void showAllocated ()
void showFree ()
void showMemory ()
int isEmpty ()
Variables
char showBuffer [200]
int heapStart
Function Documentation
int allocateMem (u32int memory)
Procedure: allocateMem
Description: Allocates memory from the heap based on the first fit method and moves the memory block into the allocate list
Parameters: int size – the number of bytes that will be allocated for a memory block
Returns: int –error code (-1 if error occurs, 0 if successful)
Definition at line 9 of file memory_commands.c.
References allocate().
{
     return allocate(memory);
 }
int initializeHeap (int size)
Procedure: initializeHeap
Description: Allocates the memory available for the heap
Parameters: int size – the number of bytes that will be allocated for the heap
Returns: int –error code (-1 if error occurs, 0 if successful)
Definition at line 5 of file memory_commands.c.
References setupHeap().
{
     return setupHeap(size);
 }
int isEmpty ()
Procedure: isEmpty
Description: Determines if the heap is empty (the allocated list is empty)
Parameters: None
Returns: Int (Either 1 or 0)
Definition at line 117 of file memory_commands.c.
References FALSE, lengthAllocated(), and TRUE.
              {
     int allocatedLen =lengthAllocated();
     if (allocatedLen == 0){
     return TRUE;
     }
     return FALSE;
 }
void showAllocated ()
Procedure: showAllocated
Description: Prints each memory block's address and size from the allocated list.
Parameters: None
Returns: Void
Definition at line 17 of file memory_commands.c.
References cmcb::beginningAddress, count, DEFAULT_DEVICE, getAllocatedList(), list::head, heapStart, itoa(), lengthAllocated(), memset(), cmcb::next, NULL, showBuffer, cmcb::size, strcat(), strcpy(), strlen(), sys_req(), and WRITE.
                     {
     int count = 0;
     int BlockCount = 1;
     List* allocatedList = getAllocatedList();
     CMCB* current;
     int allocatedLen = lengthAllocated();
     if(allocatedLen > 0){
         memset( showBuffer, '\0', sizeof(showBuffer));
     strcpy(showBuffer, "------ALLOCATED LIST--------------------------------------------------\n");
     count = strlen(showBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
         current = allocatedList->head;
         while(current!= NULL){
             count = 0;
       memset( showBuffer, '\0', sizeof(showBuffer));
             //block
             strcpy(showBuffer, "Block: ");
             char countBuf[sizeof(int)*4+1];
             itoa(BlockCount, countBuf, sizeof(countBuf));
             strcat(showBuffer, countBuf);
             //address
             strcat(showBuffer, "\nOffset: ");
             char addressBuf[sizeof(int)*4+1];
             itoa((int) current->beginningAddress  + sizeof(CMCB) - heapStart, addressBuf, sizeof(addressBuf));
             strcat(showBuffer, addressBuf);
             //size
             strcat(showBuffer, "\nSize: ");
             char sizeBuf[sizeof(int)*4+1];
             itoa((int) current->size,sizeBuf,sizeof(sizeBuf));
             strcat(showBuffer, sizeBuf);
             strcat(showBuffer, "\n\n");
             count = strlen(showBuffer);
       sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
             current = current->next;
             BlockCount++;
         }
     }
     else{
         memset( showBuffer, '\0', sizeof(showBuffer));
         strcpy(showBuffer, "ALLOCATED LIST IS EMPTY");
         strcat(showBuffer, "\n\n");
         count = strlen(showBuffer);
         sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     }
   return;
 }
void showFree ()
Procedure: showFree
Description: Prints each memory block's address and size from the free list.
Parameters: None
Returns: Void
Definition at line 65 of file memory_commands.c.
References cmcb::beginningAddress, count, DEFAULT_DEVICE, getFreeList(), list::head, heapStart, itoa(), lengthFree(), memset(), cmcb::next, NULL, showBuffer, cmcb::size, strcat(), strcpy(), strlen(), sys_req(), and WRITE.
                {
     int count = 0;
     int BlockCount = 1;
     List* freeList = getFreeList();
     CMCB* current;
     int freeLen = lengthFree();
     if(freeLen > 0){
         memset( showBuffer, '\0', sizeof(showBuffer));
     strcpy(showBuffer, "------FREE LIST--------------------------------------------------\n");
     count = strlen(showBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
         current = freeList->head;
         while(current!= NULL){
             count = 0;
       memset( showBuffer, '\0', sizeof(showBuffer));
             //block
             strcpy(showBuffer, "Block: ");
             char countBuf[sizeof(int)*4+1];
             itoa(BlockCount, countBuf, sizeof(countBuf));
             strcat(showBuffer, countBuf);
             //address
             strcat(showBuffer, "\nOFFSET: ");
             char addressBuf[sizeof(int)*4+1];
             itoa((int) current->beginningAddress + sizeof(CMCB) - heapStart, addressBuf, sizeof(addressBuf));
             strcat(showBuffer, addressBuf);
             //size
             strcat(showBuffer, "\nSIZE: ");
             char sizeBuf[sizeof(int)*4+1];
             itoa((int) current->size,sizeBuf,sizeof(sizeBuf));
             strcat(showBuffer, sizeBuf);
             strcat(showBuffer, "\n\n");
             count = strlen(showBuffer);
       sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
             current = current->next;
         }
     }
     else{
         memset( showBuffer, '\0', sizeof(showBuffer));
         strcpy(showBuffer, "FREE LIST IS EMPTY");
         strcat(showBuffer, "\n\n");
         count = strlen(showBuffer);
         sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     }
   return;
 }
void showMemory ()
Procedure: showMemory
Description: Prints each memory block's address and size from both the allocate and free lists.
Parameters: None
Returns: Void
Definition at line 112 of file memory_commands.c.
References showAllocated(), and showFree().
                  {
         showFree();
         showAllocated();
 }
Variable Documentation
int heapStart
Definition at line 9 of file memory_lists.c.
char showBuffer[200]
Definition at line 2 of file memory_commands.c.