Knuckles OS: modules/mpx_supt.h File Reference
mpx_supt.h File Reference
#include <system.h>
Classes
struct param
Macros
#define EXIT 0
#define IDLE 1
#define READ 2
#define WRITE 3
#define INVALID_OPERATION 4
#define TRUE 1
#define FALSE 0
#define MODULE_R1 0
#define MODULE_R2 1
#define MODULE_R3 2
#define MODULE_R4 4
#define MODULE_R5 8
#define MODULE_F 9
#define IO_MODULE 10
#define MEM_MODULE 11
#define INVALID_BUFFER 1000
#define INVALID_COUNT 2000
#define DEFAULT_DEVICE 111
#define COM_PORT 222
Functions
int sys_req (int op_code, int device_id, char *buffer_ptr, int *count_ptr)
void mpx_init (int cur_mod)
void sys_set_malloc (u32int(*func)(u32int))
void sys_set_free (int(*func)(void *))
void sys_set_read (int(*func)(char *, int *))
void * sys_alloc_mem (u32int size)
int sys_free_mem (void *ptr)
void idle ()
Macro Definition Documentation
#define COM_PORT 222
Definition at line 29 of file mpx_supt.h.
#define DEFAULT_DEVICE 111
Definition at line 28 of file mpx_supt.h.
#define EXIT 0
Definition at line 6 of file mpx_supt.h.
#define FALSE 0
Definition at line 13 of file mpx_supt.h.
#define IDLE 1
Definition at line 7 of file mpx_supt.h.
#define INVALID_BUFFER 1000
Definition at line 25 of file mpx_supt.h.
#define INVALID_COUNT 2000
Definition at line 26 of file mpx_supt.h.
#define INVALID_OPERATION 4
Definition at line 10 of file mpx_supt.h.
#define IO_MODULE 10
Definition at line 21 of file mpx_supt.h.
#define MEM_MODULE 11
Definition at line 22 of file mpx_supt.h.
#define MODULE_F 9
Definition at line 20 of file mpx_supt.h.
#define MODULE_R1 0
Definition at line 15 of file mpx_supt.h.
#define MODULE_R2 1
Definition at line 16 of file mpx_supt.h.
#define MODULE_R3 2
Definition at line 17 of file mpx_supt.h.
#define MODULE_R4 4
Definition at line 18 of file mpx_supt.h.
#define MODULE_R5 8
Definition at line 19 of file mpx_supt.h.
#define READ 2
Definition at line 8 of file mpx_supt.h.
#define TRUE 1
Definition at line 12 of file mpx_supt.h.
#define WRITE 3
Definition at line 9 of file mpx_supt.h.
Function Documentation
void idle ()
Procedure: idle
Description: The idle process.
Parameters: None
Returns: Void
Definition at line 186 of file mpx_supt.c.
References count, DEFAULT_DEVICE, IDLE, memset(), NULL, strcpy(), strlen(), sys_req(), and WRITE.
 {
   char msg[30];
   int count=0;
     memset( msg, '\0', sizeof(msg));
     strcpy(msg, "IDLE PROCESS EXECUTING.\n");
     count = strlen(msg);
   while(1){
     sys_req( WRITE, DEFAULT_DEVICE, msg, &count);
     sys_req(IDLE, DEFAULT_DEVICE, NULL, NULL);
   }
 }
void mpx_init (int cur_mod)
Procedure: mpx_init
Description: Initialize MPX support software.
Parameters: int cur_mod – symbolic constants MODULE_R1, MODULE_R2, etc
Returns: Void
Definition at line 109 of file mpx_supt.c.
References current_module, IO_MODULE, MEM_MODULE, and TRUE.
 {
   current_module = cur_mod;
   if (cur_mod == MEM_MODULE)
         mem_module_active = TRUE;
   if (cur_mod == IO_MODULE)
         io_module_active = TRUE;
 }
void* sys_alloc_mem (u32int size)
Procedure: sys_alloc_mem
Description: Allocates a block of memory (similar to malloc).
Parameters: number of bytes to allocate
Returns: Void
Definition at line 157 of file mpx_supt.c.
References kmalloc().
 {
   if (!mem_module_active)
     return (void *) kmalloc(size);
   else
     return (void *) (*student_malloc)(size);
 }
int sys_free_mem (void * ptr)
Procedure: sys_free_mem
Description: Frees memory.
Parameters: pointer to block of memory to free
Returns: int – success or failure (-1)
Definition at line 171 of file mpx_supt.c.
References student_free.
 {
   if (mem_module_active)
     return (*student_free)(ptr);
   // otherwise we don't free anything
   return -1;
 }
int sys_req (int op_code, int device_id, char * buffer_ptr, int * count_ptr)
Procedure: sys_req
Description: Generate interrupt 60H.
Parameters: int op_code – one of (IDLE, EXIT, READ, WRITE)
Returns: int – size of characters in the buffer
Definition at line 49 of file mpx_supt.c.
References param::buffer_ptr, param::count_ptr, param::device_id, EXIT, IDLE, INVALID_BUFFER, INVALID_COUNT, INVALID_OPERATION, NULL, param::op_code, READ, serial_print(), student_read, and WRITE.
 {
     int return_code =0;
   if (op_code == IDLE || op_code == EXIT){
     // store the process's operation request
     // triger interrupt 60h to invoke
     params.op_code = op_code;
     asm volatile ("int $60");
   }// idle or exit
   else if (op_code == READ || op_code == WRITE)
 {
     // validate buffer pointer and count pointer
     if (buffer_ptr == NULL)
         return_code = INVALID_BUFFER;
       else if (count_ptr == NULL || *count_ptr <= 0)
         return_code = INVALID_COUNT;
 // if parameters are valid store in the params structure
     if ( return_code == 0){
         params.op_code = op_code;
         params.device_id = device_id;
         params.buffer_ptr = buffer_ptr;
         params.count_ptr = count_ptr;
         if (!io_module_active){
         // if default device
           if (op_code == READ)
              return_code = student_read(buffer_ptr,count_ptr);
                else //must be WRITE
              return_code = serial_print(buffer_ptr);
         } // end reading
         }// NOT IO_MODULE
        else // I/O module is implemented
          asm volatile ("int $60");
 } // read or write
 else return_code = INVALID_OPERATION;
 return return_code;
 }// end of sys_req
void sys_set_free (int(*)(void *) func)
Procedure: sys_set_free
Description: Sets the memory free function for sys_free_mem.
Parameters: s1 – destination s2 – source
Returns: Void
Definition at line 147 of file mpx_supt.c.
References student_free.
 {
   student_free = func;
 }
void sys_set_malloc (u32int(*)(u32int) func)
Procedure: sys_set_malloc
Description: Sets the memory allocation function for sys_alloc_mem.
Parameters: function pointer
Returns: Void
Definition at line 137 of file mpx_supt.c.
References student_malloc.
 {
   student_malloc = func;
 }
void sys_set_read (int(*)(char *, int *) func)
Procedure: sys_set_read
Description: Sets the default function for reading input from the keyboard, to the function developed by the students.
Parameters: Function pointer
Returns: Void