Knuckles OS: modules/R2/pcb.c File Reference
pcb.c File Reference
#include "pcb.h"
Functions
PCB * AllocatePCB ()
PCB * SetupPCB (char *name, int classID, int priority)
error_t FreePCB (PCB *pcb)
error_t changeState (PCB *pcb, int state)
Function Documentation
PCB* AllocatePCB ()
Procdure: AllocatePCB
Description: Allocates memory for PCB and stack. Performs necessary initialization for PCB.
Parameters: None
Returns: Pointer to created PCB -OR- NULL if error occurred during allocation
Definition at line 3 of file pcb.c.
References pcb::next, NULL, PCB_STACK_SIZE, pcb::previous, pcb::stackBase, pcb::stackTop, and sys_alloc_mem().
                   {
   PCB* pcb = (PCB*)sys_alloc_mem(sizeof(PCB*));
   if(pcb){
     pcb->stackBase = sys_alloc_mem(PCB_STACK_SIZE);
     pcb->stackTop = pcb->stackBase + PCB_STACK_SIZE - sizeof(Context);
     pcb->previous = NULL;
     pcb->next = NULL;
   }
   return pcb;
   }
error_t changeState (PCB * pcb, int state)
Procedure: changeState
Description:
Parameters: PCB* pcb - Name of the modified process
        int state - New process state
Returns: Error code corrseponding to the success or failure of operation
Definition at line 43 of file pcb.c.
References blocked, E_NONE, E_NULL_PTR, E_PARAMS, ready, running, and pcb::state.
{
   if(!pcb){
     return E_NULL_PTR;
   }
   if(state == ready){
     pcb->state = ready;
   } else if(state == running){
     pcb->state = running;
   } else if(state == blocked){
     pcb->state = blocked;
   } else{
     return E_PARAMS;
   }
   return E_NONE;
 }
error_t FreePCB (PCB * pcb)
Procedure: FreePCB
Description: Frees all memory given to a PCB.
Parameters: PCB* pcb - pointer to the pcb to be freed
Returns: Error code corrseponding to the success or failure of operation
Definition at line 27 of file pcb.c.
References E_FREE_MEM, E_NONE, NULL, pcb::stackBase, and sys_free_mem().
{
   error_t error = E_NONE;
   if(pcb == NULL){
     // PCB is already free
     return E_NONE;
   }
   if(sys_free_mem(pcb->stackBase) == -1){
     error = E_FREE_MEM;
   }
   if(sys_free_mem(pcb) == -1){
     error = E_FREE_MEM;
   }
   return error;
 }
PCB* SetupPCB (char * name, int classID, int priority)
Procedure: SetupPCB
Description: Calls AllocatePCB to create a new empty PCB. The PCB information is initialized. The PCB state is set to ready and not suspended.
Parameters: char* name - Name of the setup process
        int classID - Class of the setup process
        int priority - Prioriyt of setup process
Returns: Pointer to setup PCB -OR- NULL if error occurred during setup
Definition at line 14 of file pcb.c.
References AllocatePCB(), application_process, pcb::classID, pcb::isSuspended, pcb::name, NULL, PCB_NAME_SIZE, PCB_PRIORITY_MAX, PCB_PRIORITY_MIN, pcb::priority, ready, pcb::state, strcpy(), and strlen().
{
   if(!((strlen(name) < PCB_NAME_SIZE) && (classID <= application_process) && (PCB_PRIORITY_MIN <= priority && priority <= PCB_PRIORITY_MAX))){
     return NULL;
   }
   PCB* pcb = AllocatePCB();
   strcpy(pcb->name, name);
   pcb->classID = classID;
   pcb->priority = priority;
   pcb->state = ready;
   pcb->isSuspended = false; // unsuspended
   return pcb;
 }