Knuckles OS: modules/polling.h File Reference
polling.h File Reference
#include <string.h>
#include <core/io.h>
#include <core/serial.h>
#include "mpx_supt.h"
Macros
#define COM1 0x3f8
#define BACKSPACE 0x7F
#define CR 0x0D
#define ESC 0x1B
#define UP 0x41
#define DOWN 0x42
#define RIGHT 0x43
#define LEFT 0X44
Functions
int polling (char *buffer, int *count)
int setCursor (int currIndex, int desIndex)
Macro Definition Documentation
#define BACKSPACE 0x7F
Definition at line 17 of file polling.h.
#define COM1 0x3f8
Definition at line 14 of file polling.h.
#define CR 0x0D
Definition at line 18 of file polling.h.
#define DOWN 0x42
Definition at line 22 of file polling.h.
#define ESC 0x1B
Definition at line 19 of file polling.h.
#define LEFT 0X44
Definition at line 24 of file polling.h.
#define RIGHT 0x43
Definition at line 23 of file polling.h.
#define UP 0x41
Definition at line 21 of file polling.h.
Function Documentation
int polling (char * buffer, int * count)
Procedure: poll
Description: Receives input from user through COM1. Echos characters to command line and handles special characters.
Parameters: char *buffer – Accepts input from user int *count – Holds the number of characters in buffer
Returns: int – number of characters in the buffer
Definition at line 16 of file polling.c.
References BACKSPACE, COM1, commandNum, count, CR, DEFAULT_DEVICE, DOWN, ESC, history, inb, LEFT, memset(), NULL, RIGHT, serial_print(), setCursor(), strcpy(), strlen(), sys_alloc_mem(), sys_req(), UP, and WRITE.
{
     /* Pointer to current number of characters in buffer */
     *count = 0;
     /* Location of cursor */
     int index = 0;
     /* Size of new buffer refreshed to the screen */
     int *tempCount = 0;
     /*  */
     int commandIndex = 0;
     while(1) {
         if (inb(COM1 + 5)&1) {
             char letter = inb(COM1);
             if(letter == BACKSPACE) {
                 if(index == 0) {}
                 else {
                     index--;
                     serial_print("\b");
                     int i;
                     for(i = index; i < (*count)-1; i++) {
                         buffer[i] = buffer[i+1];
                     }
                     buffer[*count-1] = ' ';
                     buffer[*count] = NULL;
                     *tempCount = *count - index - 1;
                     char* newArray = sys_alloc_mem(*count);
                     strcpy(newArray, buffer+index);
                     serial_print(newArray);
                     (*count)--;
                     i = strlen(buffer);
                     while(i > index) {
                         i--;
                         serial_print("\b");
                     }
                 }
             }
             else if(letter == CR) {
                 if(*count > 0) {
                     history = sys_alloc_mem(*count);
                     strcpy(history, buffer);
                     commandNum = commandNum + 1;
                 }
                 commandIndex = 0;
                 serial_print("\n");
                 return *buffer;
             }
             else if(letter == ESC) {
                 char arrow[30];
                 int arrow_cnt;
                 inb(COM1);
                 char letter3 = inb(COM1);
                 if(letter3 == UP) {
                     if(commandNum == 0) {}
                     else {
                         if(commandIndex == 1) {}
                         else {
                             strcpy(buffer, history);
                             *count = strlen(buffer);
                             index = setCursor(index, 0);
                             index = strlen(buffer);
                             serial_print(buffer);
                             commandIndex++;
                         }
                     }
                 }
                 else if(letter3 == DOWN) {
                     if(commandNum == 0) {}
                     else {
                         if(commandIndex == 0) {}
                         else {
                             memset(buffer, ' ', strlen(history));
                             index = setCursor(index, 0);
                             serial_print(buffer);
                             index = strlen(buffer);
                             memset(buffer, NULL, strlen(history));
                             index = setCursor(index, 0);
                             serial_print(buffer);
                             index = strlen(buffer);
                             *count = 0;
                             index = setCursor(index, 0);
                             commandIndex--;
                         }
                     }
                 }
                 else if(letter3 == RIGHT) {
                     if(index == *count) {}
                     else {
                         index++;
                         strcpy(arrow, "\033[1C");
                         arrow_cnt = strlen(arrow);
                         sys_req(WRITE, DEFAULT_DEVICE, arrow, &arrow_cnt);
                     }
                 }
                 else if(letter3 == LEFT) {
                     if(index == 0) {}
                     else {
                         index--;
                         strcpy(arrow, "\033[1D");
                         arrow_cnt = strlen(arrow);
                         sys_req(WRITE, DEFAULT_DEVICE, arrow, &arrow_cnt);
                     }
                 }
                 else if(letter3 == 0x33) {
                     char letter4 = inb(COM1);
                     if(letter4 == 0x7E) {
                         if(index == *count) {}
                         else {
                             int i;
                             for(i = index; i < (*count)-1; i++) {
                                 buffer[i] = buffer[i+1];
                             }
                             buffer[*count-1] = ' ';
                             buffer[*count] = NULL;
                             *tempCount = *count - index - 1;
                             char* newArray = sys_alloc_mem(*count);
                             strcpy(newArray, buffer+index);
                             serial_print(newArray);
                             (*count)--;
                             i = strlen(buffer);
                             while(i > index) {
                                 i--;
                                 serial_print("\b");
                             }
                         }
                     }
                 }
             }
             else {
                 if(*count == 64) {}
                 else {
                     int i;
                     for(i = *count; i > index; i--) {
                         buffer[i] = buffer[i-1];
                     }
                     buffer[index] = letter;
                     *count += 1;
                     index += 1;
                     *tempCount = *count - index - 1;
                     char* newArray = sys_alloc_mem(*count);
                     strcpy(newArray, buffer+index - 1);
                     serial_print(newArray);
                     i = *count;
                     while(i > index) {
                         i--;
                         serial_print("\b");
                     }
                 }
             }
         }
     }
 }
int setCursor (int currIndex, int desIndex)
Procedure: setCursor
Description: Sets the cursor to an index.
Parameters: int currIndex – current index of the cursor int desIndex – destination index of the cursor
Returns: int – new index of the cursor
Definition at line 175 of file polling.c.
References serial_print().
{
     while(currIndex > desIndex) {
         serial_print("\b");
         currIndex -= 1;
     }
     return currIndex;
 }