Knuckles OS: modules/R2/process_queue.h File Reference
process_queue.h File Reference
#include "pcb.h"
#include <string.h>
#include <core/serial.h>
Classes
struct Queue
Struct to hold queue information.
Functions
PCB * FindPCB (char *name)
error_t InsertPCB (PCB *pcb)
error_t RemovePCB (PCB *pcb)
void setupQueues ()
int lengthReady ()
int lengthBlocked ()
error_t addReady (PCB *pcb)
error_t addBlocked (PCB *pcb)
int getIndexReady (char *name)
int getIndexBlocked (char *name)
PCB * getPCBReady (int index)
PCB * getPCBBlocked (int index)
error_t removePCBAtIndexReady (int index)
error_t removePCBAtIndexBlocked (int index)
PCB * peekReady ()
PCB * peekBlocked ()
PCB * popReady ()
PCB * popBlocked ()
error_t addReadyAtEnd (PCB *pcb)
Function Documentation
error_t addBlocked (PCB * pcb)
Procedure: addBlocked
Description: Adds the input PCB to the blocked queue.
Parameters: PCB* pcb – PCB to be added
Returns: Error code corresponding to the success or failure of operation
Definition at line 74 of file process_queue.c.
References Queue::count, E_NONE, Queue::head, pcb::next, NULL, pcb::previous, and Queue::tail.
{
   if(blocked_queue.count == 0){ // is empty?
         pcb->next = NULL;
         pcb->previous = NULL;
         blocked_queue.head = pcb;
     } else{
         pcb->previous = blocked_queue.tail;
         blocked_queue.tail->next = pcb;
     }
     blocked_queue.tail = pcb;
     blocked_queue.count++;
   return E_NONE;
 }
error_t addReady (PCB * pcb)
Procedure: addReady
Description: Initializes the global queues (ready and blocked).
Parameters: None
Returns: Void
Definition at line 88 of file process_queue.c.
References Queue::count, E_NONE, Queue::head, pcb::next, NULL, pcb::previous, pcb::priority, and Queue::tail.
{
   error_t errorCode;
   PCB* current = ready_queue.head;
     if(ready_queue.count == 0){ // is empty?
         pcb->next = NULL;
         pcb->previous = NULL;
         current = pcb;
     } else{
         while(current->next != NULL && pcb-> priority >= current-> priority){
             current = current->next;
         }
         if(pcb->priority < current->priority){
             pcb->next = current;
             pcb->previous = current->previous;
             if(current->previous != NULL) { // at head?
                 pcb->previous->next = pcb;
             }
             current->previous = pcb;
         } else{ // insert at tail
             pcb->next = NULL;
             pcb->previous = current;
             current->next = pcb;
         }
     }
     if(pcb->previous == NULL){
         ready_queue.head = pcb;
     }
     if(pcb->next == NULL){
         ready_queue.tail = pcb;
     }
     ready_queue.count++;
   errorCode = E_NONE;
   return errorCode;
 }
error_t addReadyAtEnd (PCB * pcb)
Procedure: addReadyAtEnd
Description: Adds the PCB to the tail of the ready queue
Parameters: PCB* pcb – PCB to be added to the end of the ready queue
Returns: Error code corresponding to the success or failure of operation
Definition at line 279 of file process_queue.c.
References Queue::count, E_NONE, Queue::head, pcb::next, NULL, pcb::previous, and Queue::tail.
{
     error_t errorCode;
   PCB* current = ready_queue.tail;
     if(ready_queue.count == 0) {
         pcb->next = NULL;
         pcb->previous = NULL;
         current = pcb;
         ready_queue.head = pcb;
         ready_queue.tail = pcb;
     }
     else {
         current->next = pcb;
         pcb->previous = current;
         pcb->next = NULL;
         ready_queue.tail = pcb;
     }
     ready_queue.count++;
   errorCode = E_NONE;
     return errorCode;
 }
PCB* FindPCB (char * name)
Procedure: FindPCB
Description: Searches for and returns the PCB mataching the name of the input name.
Parameters: char* name – name of the PCB (min. 8 characters, max. 30 characters)
Returns: Pointer to the returned PCB -OR- NULL if the PCB was not found
Definition at line 23 of file process_queue.c.
References Queue::head, pcb::name, pcb::next, NULL, and strcmp().
{
   PCB* current = ready_queue.head;
   while(current != NULL){
     if(!strcmp(current->name, name))
       return current;
     current = current->next;
   }
   current = blocked_queue.head;
   while(current != NULL){
     if(!strcmp(current->name, name))
       return current;
     current = current->next;
   }
   return NULL; // Not found
 }
int getIndexBlocked (char * name)
Procedure: getIndexBlocked
Description: Fetches the index of the input PCB name in the blocked queue.
Parameters: char* name – name of the PCB to lookup
Returns: Index of the input name's corresponding PCB in the blocked queue
Definition at line 138 of file process_queue.c.
References Queue::head, pcb::name, pcb::next, NULL, and strcmp().
{
   int index = -1; // name not found
   PCB* current = blocked_queue.head;
   int i = 0;
     while(current != NULL){
         if(!strcmp(name, current->name)){
             index = i;
             break;
         }
     current = current->next;
         i++;
     }
     return index;
 }
int getIndexReady (char * name)
Procedure: getIndexReady
Description: Fetches the index of the input PCB name in the ready queue.
Parameters: char* name – name of the PCB to lookup
Returns: Index of the input name's corresponding PCB in the ready queue -OR- -1 if the index was not found
Definition at line 123 of file process_queue.c.
References Queue::head, pcb::name, pcb::next, NULL, and strcmp().
{
   int index = -1; // name not found
   PCB* current = ready_queue.head;
   int i = 0;
     while(current != NULL){
         if(!strcmp(name, current->name)){
             index = i;
             break;
         }
     current = current->next;
         i++;
     }
     return index;
 }
PCB* getPCBBlocked (int index)
Procedure: getPCBBlocked
Description: Fetches a pointer to the PCB at the input index within the blocked queue.
Parameters: int index – index of the blocked queue
Returns: Pointer to the fetched PCB from the blocked queue -OR- NULL if the PCB was not found
Definition at line 168 of file process_queue.c.
References Queue::count, Queue::head, pcb::next, and NULL.
{
   PCB* pcb = blocked_queue.head;
     if(index < 0 || index >= blocked_queue.count){
         return NULL;
     } else{
         int i = 0;
     while(i < index){
       pcb = pcb->next;
       i++;
     }
     }
   return pcb;
 }
PCB* getPCBReady (int index)
Procedure: getPCBReady
Description: Fetches a pointer to the PCB at the input index within the ready queue.
Parameters: int index – index of the ready queue
Returns: Pointer to the fetched PCB from the ready queue -OR- NULL if the PCB was not found
Definition at line 154 of file process_queue.c.
References Queue::count, Queue::head, pcb::next, and NULL.
{
   PCB* pcb = ready_queue.head;
     if(index < 0 || index >= ready_queue.count){
         return NULL;
     } else{
         int i = 0;
     while(i < index){
       pcb = pcb->next;
       i++;
     }
     }
   return pcb;
 }
error_t InsertPCB (PCB * pcb)
Procedure: InsertPCB
Description: Inserts the input PCB to its appropriate queue.
Parameters: PCB* pcb – PCB to insert into a queue
Returns: Error code corresponding to the success or failure of operation
Definition at line 41 of file process_queue.c.
References addBlocked(), addReady(), blocked, E_NULL_PTR, E_PARAMS, ready, running, and pcb::state.
{
   if(!pcb){
     return E_NULL_PTR;
   }
   if(pcb->state == running){
     return E_PARAMS;
   }
   error_t errorCode;
   if(pcb->state == blocked){
     errorCode = addBlocked(pcb);
   }
   if(pcb->state == ready){
     errorCode = addReady(pcb);
   }
   return errorCode;
 }
int lengthBlocked ()
Procedure: lengthBlocked
Description: Fetches the length of the blocked queue.
Parameters: None
Returns: Length of the blocked queue
Definition at line 19 of file process_queue.c.
References Queue::count.
                    {
     return blocked_queue.count;
 }
int lengthReady ()
Procedure: lengthReady
Description: Fetches the length of the ready queue.
Parameters: None
Returns: Length of the ready queue
Definition at line 15 of file process_queue.c.
References Queue::count.
                  {
     return ready_queue.count;
 }
PCB* peekBlocked ()
Procedure: peekBlocked
Description: Returns the head of the blocked queue.
Parameters: None
Returns: PCB* at the head of the blocked queue.
Definition at line 249 of file process_queue.c.
References Queue::head.
                   {
     return blocked_queue.head;
 }
PCB* peekReady ()
Procedure: peekReady
Description: Returns the head of the ready queue.
Parameters: None
Returns: PCB* at the head of the ready queue.
Definition at line 245 of file process_queue.c.
References Queue::head.
                 {
     return ready_queue.head;
 }
PCB* popBlocked ()
Procedure: popBlocked
Description: Returns the head of the blocked queue and removes it from the blocked queue.
Parameters: None
Returns: PCB* at the head of the blocked queue.
Definition at line 268 of file process_queue.c.
References Queue::count, Queue::head, pcb::next, NULL, and pcb::previous.
                  {
     PCB *trav = blocked_queue.head;
     if (blocked_queue.head != NULL) {
         blocked_queue.head = blocked_queue.head->next;
         blocked_queue.head->previous = NULL;
         trav->next = NULL;
         blocked_queue.count--;
     }
     return trav;
 }
PCB* popReady ()
Procedure: popReady
Description: Returns the head of the ready queue and removes it from the ready queue.
Parameters: None
Returns: PCB* at the head of the ready queue.
Definition at line 253 of file process_queue.c.
References Queue::count, Queue::head, pcb::next, NULL, pcb::previous, and serial_println().
                {
     PCB *trav = ready_queue.head;
     if (ready_queue.head != NULL) {
         ready_queue.head = ready_queue.head->next;
         ready_queue.head->previous = NULL;
         trav->next = NULL;
         ready_queue.count--;
     }
     else {
         serial_println("Nothing to pop!");
     }
     return trav;
 }
error_t RemovePCB (PCB * pcb)
Procedure: RemovePCB
Description: Removes the input PCB to its appropriate queue.
Parameters: PCB* pcb – PCB to remove from its queue
Returns: Error code corresponding to the success or failure of operation
Definition at line 58 of file process_queue.c.
References blocked, E_NOT_FOUND, E_PARAMS, getIndexBlocked(), getIndexReady(), pcb::name, ready, removePCBAtIndexBlocked(), removePCBAtIndexReady(), and pcb::state.
{
   error_t errorCode;
   if(!pcb){
     return E_NOT_FOUND;
   }
   if(pcb->state == ready){
     errorCode = removePCBAtIndexReady(getIndexReady(pcb->name));
   }
   else if(pcb->state == blocked){
     errorCode = removePCBAtIndexBlocked(getIndexBlocked(pcb->name));
   } else{
     errorCode = E_PARAMS;
   }
   return errorCode;
 }
error_t removePCBAtIndexBlocked (int index)
Procedure: removePCBAtIndexQueue
Description: Removes the PCB from the blocked queue corresponding to the input index.
Parameters: int index – index of the blocked queue
Returns: Error code corresponding to the success or failure of operation
Definition at line 214 of file process_queue.c.
References Queue::count, E_NONE, E_NULL_PTR, Queue::head, pcb::next, NULL, pcb::previous, and Queue::tail.
{
   PCB* pcb = blocked_queue.head;
     if(index < 0 || index >= blocked_queue.count){
         return E_NULL_PTR;
     } else{
         int i = 0;
     while(i < index){
       pcb = pcb->next;
       i++;
     }
     }
     if(index == 0){ // at head
         blocked_queue.head = pcb->next;
     }
     if(index == blocked_queue.count - 1){ // at tail
         blocked_queue.tail = pcb->previous;
     }
     if(pcb->previous != NULL){
         pcb->previous->next = pcb->next;
     }
     if(pcb->next != NULL){
         pcb->next->previous = pcb->previous;
     }
     if(pcb != NULL){
         blocked_queue.count--;
     }
     pcb->previous = NULL;
     pcb->next = NULL;
     return E_NONE;
 }
error_t removePCBAtIndexReady (int index)
Procedure: removePCBAtIndexReady
Description: Removes the PCB from the ready queue corresponding to the input index.
Parameters: int index – index of the ready queue
Returns: Error code corresponding to the success or failure of operation
Definition at line 182 of file process_queue.c.
References Queue::count, E_NONE, E_NULL_PTR, Queue::head, pcb::next, NULL, pcb::previous, and Queue::tail.
{
   PCB* pcb = ready_queue.head;
     if(index < 0 || index >= ready_queue.count){
         return E_NULL_PTR;
     } else{
         int i = 0;
     while(i < index){
       pcb = pcb->next;
       i++;
     }
     }
     if(index == 0){ // at head
         ready_queue.head = pcb->next;
     }
     if(index == ready_queue.count - 1){ // at tail
         ready_queue.tail = pcb->previous;
     }
     if(pcb->previous != NULL){
         pcb->previous->next = pcb->next;
     }
     if(pcb->next != NULL){
         pcb->next->previous = pcb->previous;
     }
     if(pcb != NULL){
         ready_queue.count--;
     }
     pcb->previous = NULL;
     pcb->next = NULL;
     return E_NONE;
 }
void setupQueues ()
Procedure: setupQueues
Description: Initializes the global queues (ready and blocked).
Parameters: None
Returns: Void
Definition at line 5 of file process_queue.c.
References Queue::count, Queue::head, NULL, and Queue::tail.
                   {
   ready_queue.count = 0;
   ready_queue.head = NULL;
   ready_queue.tail = NULL;
   blocked_queue.count = 0;
   blocked_queue.head = NULL;
   blocked_queue.tail = NULL;
 }