Knuckles OS: modules/R2/queue_commands.c File Reference
queue_commands.c File Reference
#include "queue_commands.h"
Macros
#define UNUSED(x) (void)(x)
Functions
error_t suspend (char *name)
error_t resume (char *name)
error_t setPriority (char *name, int priority)
void show (char *name)
void showAll ()
void showReady ()
void showBlocked ()
error_t create (char *name, int pClass, int priority)
error_t remove (char *name)
error_t block (char *name)
error_t unblock (char *name)
Variables
char showBuffer [2500]
int count
Macro Definition Documentation
#define UNUSED (x) (void)(x)
Definition at line 3 of file queue_commands.c.
Function Documentation
error_t block (char * name)
Procedure: block
Description: Sets a PCB to blocked and reinserts it into the appropriate queue.
Parameters: char* name – name of the PCB to be blocked
Returns: Error code corrseponding to the success or failure of operation
Definition at line 271 of file queue_commands.c.
References blocked, E_NONE, FindPCB(), InsertPCB(), RemovePCB(), and pcb::state.
{
     PCB *pcb = FindPCB(name);
     error_t error = RemovePCB(pcb);
     pcb->state = blocked;
     if(error == E_NONE) {
         error = InsertPCB(pcb);
     }
     return error;
 }
error_t create (char * name, int pClass, int priority)
Procedure: create
Description: Create PCB and insert into the appropriate queue.
Parameters: char* name – name of the created PCB
        int pClass -- integer representation of the process class
        int priority -- integer representation of the PCB's priority
Returns: Error code corrseponding to the success or failure of operation
Definition at line 253 of file queue_commands.c.
References E_EXISTS, FindPCB(), InsertPCB(), NULL, and SetupPCB().
{
     error_t error;
     if(FindPCB(name) == NULL) {
         PCB *pcb = SetupPCB(name, pClass, priority);
         error = InsertPCB(pcb);
     }
     else {
         error = E_EXISTS;
     }
   return error;
 }
error_t remove (char * name)
Procedure: remove
Description: Removes a PCB from the appropriate queue and frees all associated memory.
Parameters: char* name – name of the PCB to be removed
Returns: Error code corrseponding to the success or failure of operation
Definition at line 265 of file queue_commands.c.
References FindPCB(), pcb::name, and RemovePCB().
{
     PCB *pcb = FindPCB(name);
     error_t error = RemovePCB(pcb);
   return error;
 }
error_t resume (char * name)
Procedure: resume
Description: Unsuspends the PCB and reinserts it in the appropriate queue.
Parameters: char* name – name of the PCB
Returns: Void
Definition at line 23 of file queue_commands.c.
References E_NONE, E_NOT_FOUND, E_STATE, FindPCB(), pcb::isSuspended, and NULL.
{
   error_t error;
   PCB* pcb = FindPCB(name);
   if(pcb == NULL){
     error = E_NOT_FOUND;
   }
   else if(pcb->isSuspended == false){
     error = E_STATE;
   }
   else{
     pcb->isSuspended = false;
         error = E_NONE;
   }
   return error;
 }
error_t setPriority (char * name, int priority)
Procedure: setPriority
Description: Sets the priority of a selected queue and reinserts it into the correct queue.
Parameters: char* name – name of the PCB
        int priority -- integer representation of the PCB's priority
Returns: Void
Definition at line 39 of file queue_commands.c.
References E_NONE, E_NOT_FOUND, FindPCB(), InsertPCB(), NULL, pcb::priority, and RemovePCB().
{
   error_t error;
   PCB* pcb = FindPCB(name);
   if(pcb == NULL){
     error = E_NOT_FOUND;
   }
   else{
     if(pcb->priority == priority){
       error = E_NONE;
     } else{
       pcb->priority = priority;
       RemovePCB(pcb);
       InsertPCB(pcb);
       error = E_NONE;
     }
   }
   return error;
 }
void show (char * name)
Procedure: show
Description: Displays information pertaining for the PCB.
Parameters: char* name – name of the PCB
Returns: Void
Definition at line 59 of file queue_commands.c.
References application_process, blocked, pcb::classID, count, DEFAULT_DEVICE, E_NOT_FOUND, errorHandler(), FindPCB(), pcb::isSuspended, itoa(), memset(), pcb::name, NULL, pcb::priority, ready, running, showBuffer, pcb::state, strcat(), strcpy(), strlen(), sys_req(), system_process, and WRITE.
                       {
   count = 0;
   error_t error;
   PCB* pcb = FindPCB(name);
   if(pcb == NULL){
     error = E_NOT_FOUND;
     errorHandler(error);
     return;
   }
   memset( showBuffer, '\0', sizeof(showBuffer));
   strcpy(showBuffer, "------PCB--------------------------------------------------\n");
   count = strlen(showBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     memset( showBuffer, '\0', sizeof(showBuffer));
     //Name
     strcpy(showBuffer, "NAME: ");
     strcat(showBuffer, pcb->name);
     //Class
     strcat(showBuffer, "\nCLASS: ");
     if(pcb->classID == system_process){
       strcat(showBuffer, "System");
     }
     else if(pcb->classID == application_process){
       strcat(showBuffer, "Application");
     }
     //Priorty
     strcat(showBuffer, "\nPRIORITY: ");
     char priorityBuf[sizeof(int)*4+1];
     itoa(pcb->priority,priorityBuf,sizeof(priorityBuf));
     strcat(showBuffer,priorityBuf);
     //State
     strcat(showBuffer, "\nSTATE: ");
     if(pcb->state == ready){
       strcat(showBuffer, "Ready");
     }
     else if(pcb->state == running){
       strcat(showBuffer, "Running");
     }
     else if(pcb->state == blocked){
       strcat(showBuffer, "Blocked");
     }
     //Suspended?
     strcat(showBuffer, "\nSUSPENDED: ");
     if(pcb->isSuspended == false){
       strcat(showBuffer, "False");
     }
     else if(pcb->isSuspended == true){
       strcat(showBuffer, "True");
     }
     strcat(showBuffer, "\n\n");
     count = strlen(showBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     return;
 }
void showAll ()
Procedure: showAll
Description: Displays pertaining information to each PCB in the ready and blocked queues.
Parameters: None
Returns: Void
Definition at line 118 of file queue_commands.c.
References showBlocked(), and showReady().
                {
   showReady();
   showBlocked();
 }
void showBlocked ()
Procedure: showBlocked
Description: Displays pertaining information to each PCB in the blocked queue.
Parameters: None
Returns: Void
Definition at line 188 of file queue_commands.c.
References application_process, blocked, pcb::classID, count, DEFAULT_DEVICE, getPCBBlocked(), pcb::isSuspended, itoa(), lengthBlocked(), memset(), pcb::name, pcb::priority, ready, running, showBuffer, pcb::state, strcat(), strcpy(), strlen(), sys_req(), system_process, and WRITE.
                    {
   count = 0;
   int lenBlocked = lengthBlocked();
   int i;
   PCB* current;
   if(lenBlocked >0){
     memset( showBuffer, '\0', sizeof(showBuffer));
     strcpy(showBuffer, "------BLOCKED QUEUE--------------------------------------------------\n");
     count = strlen(showBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     for(i = 0; i < lenBlocked; i++){
       current = getPCBBlocked(i);
       memset( showBuffer, '\0', sizeof(showBuffer));
       //Name
       strcpy(showBuffer, "NAME: ");
       strcat(showBuffer, current->name);
       //Class
       strcat(showBuffer, "\nCLASS: ");
       if(current->classID == system_process){
         strcat(showBuffer, "System");
       }
       else if(current->classID == application_process){
         strcat(showBuffer, "Application");
       }
       //Priorty
       strcat(showBuffer, "\nPRIORITY: ");
       char priorityBuf[sizeof(int)*4+1];
       itoa(current->priority,priorityBuf,sizeof(priorityBuf));
       strcat(showBuffer,priorityBuf);
       //State
       strcat(showBuffer, "\nSTATE: ");
       if(current->state == ready){
         strcat(showBuffer, "Ready");
       }
       else if(current->state == running){
         strcat(showBuffer, "Running");
       }
       else if(current->state == blocked){
         strcat(showBuffer, "Blocked");
       }
       //Suspended?
       strcat(showBuffer, "\nSUSPENDED: ");
       if(current->isSuspended == false){
         strcat(showBuffer, "False");
       }
       else if(current->isSuspended == true){
         strcat(showBuffer, "True");
       }
       strcat(showBuffer, "\n\n");
       count = strlen(showBuffer);
       sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
      }
    }
    else{
       memset( showBuffer, '\0', sizeof(showBuffer));
       strcpy(showBuffer, "BLOCKED QUEUE IS EMPTY");
       strcat(showBuffer, "\n\n");
       count = strlen(showBuffer);
       sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     }
 }
void showReady ()
Procedure: showReady
Description: Displays pertaining information to each PCB in the ready queue.
Parameters: None
Returns: Void
Definition at line 123 of file queue_commands.c.
References application_process, blocked, pcb::classID, count, DEFAULT_DEVICE, getPCBReady(), pcb::isSuspended, itoa(), lengthReady(), memset(), pcb::name, pcb::priority, ready, running, showBuffer, pcb::state, strcat(), strcpy(), strlen(), sys_req(), system_process, and WRITE.
                  {
   count = 0;
   int lenReady = lengthReady();
   int i;
   PCB* current;
   if(lenReady > 0){
     memset( showBuffer, '\0', sizeof(showBuffer));
     strcpy(showBuffer, "------READY QUEUE--------------------------------------------------\n");
     count = strlen(showBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     for(i = 0; i < lenReady; i++){
       current = getPCBReady(i);
       count = 0;
       memset( showBuffer, '\0', sizeof(showBuffer));
       //Name
       strcpy(showBuffer, "NAME: ");
       strcat(showBuffer, current->name);
       //Class
       strcat(showBuffer, "\nCLASS: ");
       if(current->classID == system_process){
         strcat(showBuffer, "System");
       }
       else if(current->classID == application_process){
         strcat(showBuffer, "Application");
       }
       //Priorty
       strcat(showBuffer, "\nPRIORITY: ");
       char priorityBuf[sizeof(int)*4+1];
       itoa(current->priority,priorityBuf,sizeof(priorityBuf));
       strcat(showBuffer,priorityBuf);
       //State
       strcat(showBuffer, "\nSTATE: ");
       if(current->state == ready){
         strcat(showBuffer, "Ready");
       }
       else if(current->state == running){
         strcat(showBuffer, "Running");
       }
       else if(current->state == blocked){
         strcat(showBuffer, "Blocked");
       }
       //Suspended?
       strcat(showBuffer, "\nSUSPENDED: ");
       if(current->isSuspended == false){
         strcat(showBuffer, "False");
       }
       else if(current->isSuspended == true){
         strcat(showBuffer, "True");
       }
       strcat(showBuffer, "\n\n");
       count = strlen(showBuffer);
       sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
     }
   }
   else{
        memset( showBuffer, '\0', sizeof(showBuffer));
      strcpy(showBuffer, "READY QUEUE IS EMPTY");
      strcat(showBuffer, "\n\n");
      count = strlen(showBuffer);
      sys_req( WRITE, DEFAULT_DEVICE, showBuffer, &count);
    }
 }
error_t suspend (char * name)
Procedure: suspend
Description: Places the PCB in the suspended state and reinserts it in the appropriate queue.
Parameters: char* name – name of the PCB
Returns: Void
Definition at line 7 of file queue_commands.c.
References E_NONE, E_NOT_FOUND, E_STATE, FindPCB(), pcb::isSuspended, and NULL.
{
   error_t error;
   PCB* pcb = FindPCB(name);
   if(pcb == NULL){
     error = E_NOT_FOUND;
   }
   else if(pcb->isSuspended == true){
     error = E_STATE;
   }
   else{
     pcb->isSuspended = true;
         error = E_NONE;
   }
   return error;
 }
error_t unblock (char * name)
Procedure: unblock
Description: Sets a PCB to unblocked and reinserts it into the appropriate queue.
Parameters: char* name – name of the PCB to be unblocked
Returns: Error code corrseponding to the success or failure of operation
Definition at line 281 of file queue_commands.c.
References E_NONE, FindPCB(), InsertPCB(), ready, RemovePCB(), and pcb::state.
{
     PCB *pcb = FindPCB(name);
     //pcb->state = ready;
     error_t error = RemovePCB(pcb);
     pcb->state = ready;
   if(error == E_NONE) {
       error = InsertPCB(pcb);
   }
            // returns error
   return error;
 }
Variable Documentation
int count
Definition at line 5 of file queue_commands.c.
char showBuffer[2500]
Definition at line 4 of file queue_commands.c.