Knuckles OS: modules/real_time_clock.c File Reference
real_time_clock.c File Reference
#include "real_time_clock.h"
Functions
void getDate ()
void setDate (char *inputDate)
int checkDate (int day, int mon, int year)
void getTime ()
void setTime (char *inputTime)
void BCD_to_Dec (unsigned char bcd, char *conversion)
void Dec_to_BCD (date_time *writer)
void displayTime (date_time_char *time_reader)
void displayDate (date_time_char *date_reader)
date_time_char * new_time_reader ()
date_time_char * new_date_reader ()
date_time * new_time_writer ()
date_time * new_date_writer ()
void free_time_reader (date_time_char *time_reader)
void free_date_reader (date_time_char *date_reader)
void free_time_writer (date_time *time_writer)
void free_date_writer (date_time *date_writer)
Function Documentation
void BCD_to_Dec (unsigned char bcd, char * conversion)
Procedure: BCD_to_Dec
Description: Converts CPU's BCD format to a decimal (string format).
Parameters: unsigned char bcd – BCD to be converted char* conversion – pointer for the conversion to be stored
Returns: Void
Definition at line 177 of file real_time_clock.c.
 {
     *conversion++ = (bcd >> 4) + '0';
     *conversion++ = (bcd & 0x0f) + '0';
     *conversion = '\0';
   return;
 }
int checkDate (int day, int mon, int year)
Procedure: checkDate
Description: Verifies date is legitimate.
Parameters: int day – day of the month (starting at 1) int mon – month of the year (starting at 1) int year – year (2 digits)
Returns: int – true or false
Definition at line 84 of file real_time_clock.c.
{
   int isLeapYear = 0;
   if(year % 4 == 0){
     isLeapYear = 1;
   }
   if(((0 < day) && (day <= 31)) && ((mon == 1) | (mon == 3) | (mon == 5) | (mon == 7) | (mon == 8) | (mon == 10) | (mon == 12))){
     return 1;
   }
   if(((0 < day) && (day <= 30)) && ((mon == 4) | (mon == 6) | (mon == 9) | (mon == 11))){
     return 1;
   }
   if(((0 < day) && (day <= 28)) && (mon == 2)){
     return 1;
   }
   if((0 < day && day <= 29) && (mon == 2) && (isLeapYear)){
     return 1;
   }
   else{
     return 0;
   }
 }
void Dec_to_BCD (date_time * writer)
Procedure: Dec_to_BCD
Description: Converts the components of date_time to BCD.
Parameters: date_time* writer – pointer to the date_time struct
Returns: Void
Definition at line 187 of file real_time_clock.c.
References date_time::day_m, date_time::hour, date_time::min, date_time::mon, date_time::sec, and date_time::year.
{
   if(writer->hour != 0){
     writer->hour = (((writer->hour / 10) << 4) | (writer->hour % 10));
   }
   if(writer->min != 0){
     writer->min = (((writer->min / 10) << 4) | (writer->min % 10));
   }
   if(writer->sec != 0){
     writer->sec = (((writer->sec / 10) << 4) | (writer->sec % 10));
   }
   if(writer->year != 0){
     writer->year = writer->year % 100;
     writer->year = (((writer->year / 10) << 4) | (writer->year % 10));
   }
   if(writer->mon != 0){
     writer->mon = (((writer->mon / 10) << 4) | (writer->mon % 10));
   }
   if(writer->day_m != 0){
     writer->day_m = (((writer->day_m / 10) << 4) | (writer->day_m % 10));
   }
   return;
 }
void displayDate (date_time_char * date_reader)
Procedure: displayDate
Description: Prints the date to the default device [MM/DD/YY].
Parameters: date_time_char* date_reader – pointer to the date_time_char struct
Returns: Void
Definition at line 228 of file real_time_clock.c.
References count, date_time_char::day, DEFAULT_DEVICE, memset(), date_time_char::mon, strcat(), strcpy(), strlen(), sys_alloc_mem(), sys_free_mem(), sys_req(), WRITE, and date_time_char::year.
{
   int count = 0;
   int size = 100;
   char* cmdBuffer = (char*)sys_alloc_mem(size);
   memset(cmdBuffer, '\0', sizeof(cmdBuffer));
   strcpy(cmdBuffer, "Date: ");
   strcat(cmdBuffer, date_reader->mon);
   strcat(cmdBuffer, "/");
   strcat(cmdBuffer, date_reader->day);
   strcat(cmdBuffer, "/20");
   strcat(cmdBuffer, date_reader->year);
   strcat(cmdBuffer, " (mon/day/year)\n");
   count = strlen(cmdBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
   sys_free_mem(cmdBuffer);
   return;
 }
void displayTime (date_time_char * time_reader)
Procedure: displayTime
Description: Prints the time to the default device [HH/MM/SS].
Parameters: date_time_char* time_reader – struct to hold the time parameters
Returns: Void
Definition at line 210 of file real_time_clock.c.
References count, DEFAULT_DEVICE, date_time_char::hour, memset(), date_time_char::min, date_time_char::sec, strcat(), strcpy(), strlen(), sys_alloc_mem(), sys_free_mem(), sys_req(), and WRITE.
{
   int count = 0;
   int size = 100;
   char* cmdBuffer = (char*)sys_alloc_mem(size);
   memset(cmdBuffer, '\0', sizeof(cmdBuffer));
   strcpy(cmdBuffer, "Time: ");
   strcat(cmdBuffer, time_reader->hour);
   strcat(cmdBuffer, ":");
   strcat(cmdBuffer, time_reader->min);
   strcat(cmdBuffer, ":");
   strcat(cmdBuffer, time_reader->sec);
   strcat(cmdBuffer, " (hr/min/sec)\n");
   count = strlen(cmdBuffer);
   sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
   sys_free_mem(cmdBuffer);
   return;
 }
void free_date_reader (date_time_char * date_reader)
Procedure: free_time_reader
Description: Calls necessary methods to free the dynamic memory of date_time_char* date_reader and its components.
Parameters: date_time_char* date_reader – pointer to the date_time_char struct
Returns: Void
Definition at line 286 of file real_time_clock.c.
References date_time_char::day, date_time_char::mon, sys_free_mem(), and date_time_char::year.
{
   sys_free_mem(date_reader->day);
   sys_free_mem(date_reader->mon);
   sys_free_mem(date_reader->year);
   sys_free_mem(date_reader);
 }
void free_date_writer (date_time * date_writer)
Procedure: free_time_writer
Description: Calls necessary method to free the dynamic memory of date_time* date_writer.
Parameters: date_time* date_writer – pointer to the date_time struct
Returns: Void
Definition at line 297 of file real_time_clock.c.
References sys_free_mem().
{
   sys_free_mem(date_writer);
 }
void free_time_reader (date_time_char * time_reader)
Procedure: free_time_reader
Description: Calls necessary methods to free the dynamic memory of date_time_char* time_reader and its components.
Parameters: date_time_char* time_reader – pointer to the date_time_char struct
Returns: Void
Definition at line 279 of file real_time_clock.c.
References date_time_char::hour, date_time_char::min, date_time_char::sec, and sys_free_mem().
{
   sys_free_mem(time_reader->sec);
   sys_free_mem(time_reader->min);
   sys_free_mem(time_reader->hour);
   sys_free_mem(time_reader);
 }
void free_time_writer (date_time * time_reader)
Procedure: free_time_writer
Description: Calls necessary method to free the dynamic memory of date_time* time_reader.
Parameters: date_time* time_reader – pointer to the date_time struct
Returns: Void
Definition at line 293 of file real_time_clock.c.
References sys_free_mem().
{
   sys_free_mem(time_writer);
 }
void getDate ()
Procedure: getDate
Description: Fetches date from CPU and calls displayDate.
Parameters: None
Returns: Void
Definition at line 4 of file real_time_clock.c.
References BCD_to_Dec(), date_time_char::day, displayDate(), free_date_reader(), inb, date_time_char::mon, new_date_reader(), outb, RTC_BASE, RTC_DAY_MONTH, RTC_MONTH, RTC_READ, RTC_YEAR, and date_time_char::year.
               {
   unsigned char day, mon, year;
   outb(RTC_BASE, RTC_DAY_MONTH);
   day = inb(RTC_READ);
   outb(RTC_BASE, RTC_MONTH);
   mon = inb(RTC_READ);
   outb(RTC_BASE, RTC_YEAR);
   year = inb(RTC_READ);
   date_time_char* date_reader = new_date_reader();
   BCD_to_Dec(year, date_reader->year);
   BCD_to_Dec(mon, date_reader->mon);
   BCD_to_Dec(day, date_reader->day);
   displayDate(date_reader);
   free_date_reader(date_reader);
   return;
 }
void getTime ()
Procedure: getTime
Description: Fetches time from CPU and calls displayTime.
Parameters: None
Returns: Void
Definition at line 109 of file real_time_clock.c.
References BCD_to_Dec(), displayTime(), free_time_reader(), date_time_char::hour, inb, date_time_char::min, new_time_reader(), outb, RTC_BASE, RTC_HOUR, RTC_MINUTE, RTC_READ, RTC_SECOND, and date_time_char::sec.
               {
   unsigned char sec, min, hour;
   outb(RTC_BASE, RTC_SECOND);
   sec = inb(RTC_READ);
   outb(RTC_BASE, RTC_MINUTE);
   min = inb(RTC_READ);
   outb(RTC_BASE, RTC_HOUR);
   hour = inb(RTC_READ);
   date_time_char* time_reader = new_time_reader();
   BCD_to_Dec(hour, time_reader->hour);
   BCD_to_Dec(min, time_reader->min);
   BCD_to_Dec(sec, time_reader->sec);
   displayTime(time_reader);
   free_time_reader(time_reader);
   return;
 }
date_time_char* new_date_reader ()
Procedure: new_date_reader
Description: Constructor for date_time_char* struct, specifically for interpretting date parameters (char* day, mon, year).
Parameters: None
Returns: date_time_char* – struct which holds strings of date data (char* day, mon, year)
Definition at line 255 of file real_time_clock.c.
References date_time_char::day, date_time_char::mon, sys_alloc_mem(), and date_time_char::year.
{
   date_time_char* date_reader = (date_time_char*)sys_alloc_mem(36);
   date_reader->day = (char*)sys_alloc_mem(12);
   date_reader->mon = (char*)sys_alloc_mem(12);
   date_reader->year = (char*)sys_alloc_mem(12);
   return date_reader;
 }
date_time* new_date_writer ()
Procedure: new_date_writer
Description: Constructor for date_time* struct, specifically for writing date values to CPU (int day, mon, year).
Parameters: None
Returns: date_time* – struct which holds BCD (integer) values of date data (int day, mon, year)
Definition at line 271 of file real_time_clock.c.
References date_time::day_m, date_time::mon, NULL, sys_alloc_mem(), and date_time::year.
{
   date_time* date_writer = (date_time*)sys_alloc_mem(36);
   date_writer->day_m = NULL;
   date_writer->mon = NULL;
   date_writer->year = NULL;
   return date_writer;
 }
date_time_char* new_time_reader ()
Procedure: new_time_reader
Description: Constructor for date_time_char* struct, specifically for interpretting time parameters (char* sec, min, hour).
Parameters: None
Returns: date_time_char* – struct which holds strings of time data (char* sec, min, hour)
Definition at line 247 of file real_time_clock.c.
References date_time_char::hour, date_time_char::min, date_time_char::sec, and sys_alloc_mem().
{
   date_time_char* time_reader = (date_time_char*)sys_alloc_mem(36);
   time_reader->sec = (char*)sys_alloc_mem(12);
   time_reader->min = (char*)sys_alloc_mem(12);
   time_reader->hour = (char*)sys_alloc_mem(12);
   return time_reader;
 }
date_time* new_time_writer ()
Procedure: new_time_writer
Description: Constructor for date_time* struct, specifically for writing time values to CPU (int sec, min, hour).
Parameters: None
Returns: date_time* – struct which holds BCD (integer) values of time data (int sec, min, hour)
Definition at line 263 of file real_time_clock.c.
References date_time::hour, date_time::min, NULL, date_time::sec, and sys_alloc_mem().
{
   date_time* time_writer = (date_time*)sys_alloc_mem(36);
   time_writer->sec = NULL;
   time_writer->min = NULL;
   time_writer->hour = NULL;
   return time_writer;
 }
void setDate (char * inputDate)
Procedure: setDate
Description: Sets CPU date.
Parameters: char* inputDate – the date to be set ("mm/dd/yy")
Returns: Void
Definition at line 27 of file real_time_clock.c.
References atoi(), checkDate(), cli, count, date_time::day_m, Dec_to_BCD(), DEFAULT_DEVICE, free_time_writer(), memset(), date_time::mon, new_date_writer(), NULL, outb, RTC_BASE, RTC_DAY_MONTH, RTC_MONTH, RTC_READ, RTC_YEAR, sti, strcpy(), strlen(), strtok(), sys_req(), WRITE, and date_time::year.
{
   char cmdBuffer[45];
   int count = 0;
   date_time* date_writer = new_date_writer();
   int check_day, check_mon, check_year;
   char* lexeme = strtok(inputDate, "/");
   date_writer->mon = atoi(lexeme);
     check_mon = atoi(lexeme);
   lexeme = strtok(NULL, "/");
   date_writer->day_m = atoi(lexeme);
   check_day = atoi(lexeme);
   lexeme = strtok(NULL, "/");
   date_writer->year = atoi(lexeme);
     check_year = atoi(lexeme);
   if(checkDate(check_day,check_mon,check_year)){
     Dec_to_BCD(date_writer);
   }
   else{
     memset( cmdBuffer, '\0', sizeof(cmdBuffer));
     strcpy(cmdBuffer, "Input out of range, see help command.\n");
     count = strlen(cmdBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
     return;
   }
   /* Disable interrupts (per Intel doc.) */
   cli();
   outb(RTC_BASE, RTC_DAY_MONTH);
   outb(RTC_READ, date_writer->day_m);
   outb(RTC_BASE, RTC_MONTH);
   outb(RTC_READ, date_writer->mon);
   outb(RTC_BASE, RTC_YEAR);
   outb(RTC_READ, date_writer->year);
   /* Enable interrupts (per Intel doc.) */
   sti();
   /* Disable interrupts (per Intel doc.) */
   cli();
   outb(RTC_BASE, RTC_DAY_MONTH);
   outb(RTC_READ, date_writer->day_m);
   outb(RTC_BASE, RTC_MONTH);
   outb(RTC_READ, date_writer->mon);
   outb(RTC_BASE, RTC_YEAR);
   outb(RTC_READ, date_writer->year);
   /* Enable interrupts (per Intel doc.) */
   sti();
   free_time_writer(date_writer);
   return;
 }
void setTime (char * inputTime)
Definition at line 131 of file real_time_clock.c.
References atoi(), cli, count, Dec_to_BCD(), DEFAULT_DEVICE, free_time_writer(), date_time::hour, memset(), date_time::min, new_time_writer(), NULL, outb, RTC_BASE, RTC_HOUR, RTC_MINUTE, RTC_READ, RTC_SECOND, date_time::sec, sti, strcpy(), strlen(), strtok(), sys_req(), and WRITE.
{
   char cmdBuffer[45];
   int count = 0;
   date_time* time_writer = new_time_writer();
   int check_hour, check_min, check_sec;
   char* lexeme = strtok(inputTime, ":");
   time_writer->hour = atoi(lexeme);
     check_hour = atoi(lexeme);
   lexeme = strtok(NULL, ":");
   time_writer->min = atoi(lexeme);
   check_min = atoi(lexeme);
   lexeme = strtok(NULL, ":");
   time_writer->sec = atoi(lexeme);
     check_sec = atoi(lexeme);
   if(0 <= check_hour && check_hour < 24 && 0 <= check_min && check_min < 60 && 0 <= check_sec && check_sec < 60 ){
     Dec_to_BCD(time_writer);
   }
   else{
     memset( cmdBuffer, '\0', sizeof(cmdBuffer));
     strcpy(cmdBuffer, "Input out of range, see help command.\n");
     count = strlen(cmdBuffer);
     sys_req( WRITE, DEFAULT_DEVICE, cmdBuffer, &count);
     return;
   }
   /* Disable interrupts (per Intel doc.) */
   cli();
   outb(RTC_BASE, RTC_SECOND);
   outb(RTC_READ, time_writer->sec);
   outb(RTC_BASE, RTC_MINUTE);
   outb(RTC_READ, time_writer->min);
   outb(RTC_BASE, RTC_HOUR);
   outb(RTC_READ, time_writer->hour);
   /* Enable interrupts (per Intel doc.) */
   sti();
   free_time_writer(time_writer);
   return;
 }